// Live data model for the AI Functions & Settings documentation page.
// Captures every AI function, its system prompt, model role, JSON schema,
// and workflow — so the exported PDF records exactly what AI settings and
// commands were used to generate each function.

export const AI_SETTINGS = {
  modes: [
    { value: 'default', label: 'Default (platform InvokeLLM — lowest credit cost)', description: 'Routes all AI calls through base44.asServiceRole.integrations.Core.InvokeLLM. Model override still applies per-role.' },
    { value: 'custom', label: 'Custom (OpenAI-compatible endpoint)', description: 'Routes to user-supplied ai_base_url + ai_api_key + ai_model. Supports OpenAI, OpenRouter, Together, Groq, Ollama, LM Studio, etc.' },
  ],
  customFields: [
    { key: 'ai_base_url', label: 'Base URL', description: 'OpenAI-compatible API base (e.g. https://api.openai.com/v1)' },
    { key: 'ai_api_key', label: 'API Key', description: 'Bearer token sent in Authorization header' },
    { key: 'ai_model', label: 'Default Model', description: 'Model name used when no role override is set (e.g. gpt-4o, llama-3.1-70b)' },
  ],
  roles: [
    { key: 'planner_model', label: 'Planner', icon: 'Brain', description: 'High think-power agent. Reasons about architecture, design, and produces precise build plans. Used by chat, autonomous, planBackend, generateNativePrototype.', tier: 'high' },
    { key: 'coder_model', label: 'Coder', icon: 'Zap', description: 'Fast lightweight agent. Takes the planner blueprint and writes clean, efficient code. Used by chat, autonomous, generateBackend, generateTests.', tier: 'fast' },
    { key: 'reviewer_model', label: 'Reviewer', icon: 'ShieldCheck', description: 'Checks generated code for correctness, security, performance, and UI polish before commit. One retry pass on critical issues.', tier: 'balanced' },
    { key: 'diagnosis_model', label: 'Diagnosis', icon: 'Stethoscope', description: 'Analyzes build/deploy/compile errors, auto-fixes code-level issues by regenerating broken files with error context.', tier: 'balanced' },
  ],
  models: [
    { value: '', label: 'Automatic (platform default — lowest credit cost)', tier: 'auto' },
    { value: 'gpt_5_mini', label: 'GPT 5 Mini — fast lightweight (lowest cost)', tier: 'fast' },
    { value: 'gemini_3_flash', label: 'Gemini 3 Flash — fast lightweight (lowest cost)', tier: 'fast' },
    { value: 'gpt_5_4', label: 'GPT 5.4 — balanced (medium cost)', tier: 'balanced' },
    { value: 'gpt_5_6_sol', label: 'GPT 5.6 Sol — balanced (medium cost)', tier: 'balanced' },
    { value: 'gpt_5_6_luna', label: 'GPT 5.6 Luna — balanced (medium cost)', tier: 'balanced' },
    { value: 'claude_sonnet_4_6', label: 'Claude Sonnet 4.6 — high think (high cost)', tier: 'high' },
    { value: 'claude-sonnet-5', label: 'Claude Sonnet 5 — high think (high cost)', tier: 'high' },
    { value: 'gemini_3_1_pro', label: 'Gemini 3.1 Pro — high think (high cost)', tier: 'high' },
    { value: 'claude_opus_4_6', label: 'Claude Opus 4.6 — highest think (highest cost)', tier: 'high' },
    { value: 'claude_opus_4_7', label: 'Claude Opus 4.7 — highest think (highest cost)', tier: 'high' },
    { value: 'claude_opus_4_8', label: 'Claude Opus 4.8 — highest think (highest cost)', tier: 'high' },
    { value: 'kimi-k3', label: 'Kimi K3 (Moonshot) — 1M context, agentic coding (high cost)', tier: 'high' },
  ],
  invokeParams: {
    platform: 'base44.asServiceRole.integrations.Core.InvokeLLM({ prompt, response_json_schema?, model?, file_urls? })',
    custom: 'fetch(`${ai_base_url}/chat/completions`, { model, messages, temperature: 0.7, response_format? })',
    temperature: '0.7 (custom endpoint only — platform uses model defaults)',
    maxTokens: 'No cap — full output window (custom endpoint omits max_tokens so the model uses its own maximum)',
    truncationDetection: 'finish_reason === "length" → throws OUTPUT_TRUNCATED sentinel → autonomous loop reduces batch size',
    vision: 'Image URLs (png/jpg/gif/webp/svg) attached as image_url content parts; other URLs listed as text reference',
  },
};

export const AI_FUNCTIONS = [
  {
    name: 'chatWithMorpheus',
    category: 'AI Chat & Build',
    purpose: 'Core conversational AI. Sends operator message + full project files + entire conversation history to the LLM. Two-phase pipeline: Planner reasons about intent → Coder implements the plan → Reviewer checks before commit. Optional UI polish pass for web-app targets.',
    inputs: ['projectId', 'message', 'fileUrls?'],
    outputs: ['reply', 'fileOperations', 'needsClarification'],
    roles: ['planner', 'coder', 'reviewer'],
    promptName: 'SYSTEM_PROMPT + PLANNER_INSTRUCTIONS + CODER_INSTRUCTIONS',
    promptSummary: 'Morpheus persona — seasoned dev ops mentor inside the Matrix. Action over narration: when asked to build, DO IT immediately. Produce fileOperations array (path, full content, action). Never pseudocode or placeholders. Includes compile target build rules for windows-exe, mac-app, linux-binary, android-apk, ios-app, python-package, web-app, rpi-distro, arduino-firmware. Two-phase: Planner sets needsCode/needsClarification/plan; Coder implements the plan. Clarification only for genuine build-blocking ambiguity.',
    workflow: [
      'Load project, files, ENTIRE conversation history (perpetual memory)',
      'Create ChatMessage for operator input',
      'Build context: project name, description, compile target, current files, conversation history, design system block (web-app only)',
      'Phase 1 — Planner: invokeAI(role=planner) → { reply, needsCode, needsClarification, plan }',
      'Clarification gate: if needsClarification → save reply, return early (no code)',
      'Phase 2 — Coder: invokeAI(role=coder) with plan → { fileOperations }',
      'Inject design system styles.css if web-app and coder didn\'t ship one',
      'Phase 3 — Reviewer: reviewAndRetry(fileOps) → checks + one retry on critical issues',
      'Create snapshot, apply file operations to database',
      'Phase 4 — Polish (optional): if project.polish_ui → second coder call touching ONLY styling files',
      'Save Morpheus reply + review block to ChatMessage',
      'Update project status to "building" if files changed',
      'Log usage with full toolchain manifest (planner/coder/reviewer models)',
    ],
    jsonSchemas: [
      { name: 'Planner response', fields: ['reply (string)', 'needsCode (boolean)', 'needsClarification (boolean)', 'plan (string — file-by-file build plan)'] },
      { name: 'Coder response', fields: ['fileOperations [{ path, content, action: create|update|delete }]'] },
    ],
  },
  {
    name: 'autonomousBuildStep',
    category: 'AI Chat & Build',
    purpose: 'Runs ONE autonomous coding step. Planner analyzes the construct and decides what to build next → Coder implements 4-5 files max (output budgeting) → Reviewer checks. Returns isComplete when the project is production-ready. Handles output truncation by signaling the panel to retry with a smaller batch.',
    inputs: ['projectId', 'spec?'],
    outputs: ['reply', 'fileOperations', 'isComplete', 'truncated', 'plannerAssessment', 'reviewStatus', 'outputMetrics'],
    roles: ['planner', 'coder', 'reviewer'],
    promptName: 'PLANNER_PROMPT + CODER_PROMPT',
    promptSummary: 'Autonomous mode. Planner: pure reasoning — analyze construct, decide what\'s needed for complete production-ready deployable project, produce precise build plan. OUTPUT BUDGETING: plan at most 4-5 files per step (fewer if large), prioritize critical files, separate "THIS STEP" from "NEXT STEPS". Coder: implement plan precisely, 4-5 files max, each file COMPLETE. If previous step was truncated, plan ONLY 2 files. Detects truncation via finish_reason==="length" → signals panel to reduce batch.',
    workflow: [
      'Load project, files, entire conversation history',
      'Create snapshot before changes',
      'Phase 1 — Planner: invokeAI(role=planner) → { assessment, plan, isComplete }',
      'If isComplete → mark project ready, return (no coder call)',
      'Phase 2 — Coder: invokeAI(role=coder) with plan → { reply, fileOperations, isComplete }',
      'Truncation handling: if OUTPUT_TRUNCATED → set truncated=true, no files committed, panel retries smaller',
      'Phase 3 — Reviewer: reviewAndRetry(fileOps) → checks + retry on critical',
      'Apply file operations',
      'finalComplete = coder.isComplete AND reviewApproved',
      'Log usage with output metrics (tokens per phase, per-file token counts)',
    ],
    jsonSchemas: [
      { name: 'Planner response', fields: ['assessment (string)', 'plan (string — THIS STEP + NEXT STEPS)', 'isComplete (boolean)'] },
      { name: 'Coder response', fields: ['reply (string)', 'fileOperations [{ path, content, action }]', 'isComplete (boolean)'] },
    ],
  },
  {
    name: 'diagnoseIssue',
    category: 'AI Diagnosis & Auto-Fix',
    purpose: 'Unified diagnosis agent. Analyzes errors across the entire platform (deploy, compile, github, build), auto-fixes code-level issues by regenerating broken files with error context, and returns a structured action plan for remaining issues that need user action (credentials, manual steps, external links).',
    inputs: ['type (deploy|compile|github|build)', 'projectId', 'errorContext', 'components?'],
    outputs: ['diagnosis { summary, autoFixed[], needsUserAction[], totalErrors, allClear }'],
    roles: ['diagnosis', 'reviewer'],
    promptName: 'autoFixCodeErrors prompt',
    promptSummary: 'Morpheus as elite debugger. For each error: identify root cause (syntax, wrong API format, missing export, bad import, etc.), regenerate affected files with fix applied, keep other files unchanged. Returns fixes array with component, issue, fix description, and full corrected file content. Credential errors are classified separately (not sent to LLM) — they produce structured user action items with steps and links.',
    workflow: [
      'Load project + files',
      'Switch on type: deploy | compile | github | build',
      'Classify errors: credential errors → buildCredentialAction (no LLM)',
      'Auth errors → structured action item with /settings link',
      'Manual results (zip, sql-ready) → action items with download/SQL steps',
      'Code errors → autoFixCodeErrors:',
      '  Build file context (truncated to 20K chars)',
      '  Build error context (logs truncated to 8K chars, last 8K for compile)',
      '  invokeAI(role=diagnosis) with fixResponseSchema → { fixes, summary }',
      '  Reviewer: reviewAndRetry on fix fileOps → checks regenerated files',
      '  Apply file fixes to database (update existing or create new)',
      'Log usage with diagnosis type, auto-fixed items, remaining action items',
    ],
    jsonSchemas: [
      { name: 'Fix response', fields: ['fixes [{ component, issue, fix, files: [{ path, content }] }]', 'summary (string)'] },
    ],
    errorTypes: [
      { type: 'deploy', description: 'Backend deployment errors. Checks .plan.json, backend files. Credential gaps → user action. Code errors → auto-fix. ZIP/SQL-ready → manual steps with links.' },
      { type: 'compile', description: 'GitHub Actions build failures. Auth errors → connect GitHub. Build errors → auto-fix from error + logs. If no fix → action item with repo URL.' },
      { type: 'github', description: 'GitHub push errors. Auth → connect. Repo exists → rename. Rate limit → wait. Other → code-level fix attempt.' },
      { type: 'build', description: 'Autonomous build errors. Code-level → auto-fix from error + step context.' },
    ],
  },
  {
    name: 'planBackend',
    category: 'Architect (Backend Planning & Deploy)',
    purpose: 'AI backend architect. Analyzes the project\'s frontend files (or project description for standalone backend) and generates a complete backend architecture plan: database schema, API routes, auth strategy, storage, env vars, and infrastructure component recommendations with free-tier service suggestions.',
    inputs: ['projectId'],
    outputs: ['plan { summary, database, api, auth, storage, envVars, recommendations, components }', 'status'],
    roles: ['planner'],
    promptName: 'Backend architect prompt',
    promptSummary: 'Morpheus as backend architect. Analyze frontend files — identify API calls (fetch, axios, base URLs), data entities, auth expectations. Design complete backend: database tables with columns, API routes with methods, auth strategy (jwt/session/none/supabase-auth), storage type, env vars, deployment recommendations. For each component, suggest best free-tier service with 1-2 alternatives and reasons. Validates AI-suggested service IDs against known COMPONENTS list — falls back to default if hallucinated.',
    workflow: [
      'Load project + files',
      'Filter frontend files (non-backend/)',
      'Build file summary (truncated to 20K chars)',
      'Build context: standalone backend (description-based) or frontend analysis',
      'invokeAI(role=planner) with planSchema → full architecture plan',
      'Validate component IDs against known COMPONENTS list (fallback to default)',
      'Save plan as backend/.plan.json (update existing or create)',
      'Log usage (phase: backend_plan)',
    ],
    jsonSchemas: [
      { name: 'Plan response', fields: ['summary', 'database.tables [{ name, columns: [{ name, type, nullable, primary }] }]', 'api.routes [{ method, path, description }]', 'auth { strategy, details }', 'storage { type, details }', 'envVars []', 'recommendations', 'components [{ type, suggested, alternatives, reason }]'] },
    ],
  },
  {
    name: 'generateBackend',
    category: 'Architect (Backend Planning & Deploy)',
    purpose: 'Generates production-ready backend code files from the architecture plan and chosen deployment components. Uses the fast coder model. Files saved with "backend/" path prefix. Includes server entry point, route handlers, database migrations, auth middleware, config files, and README.',
    inputs: ['projectId', 'components'],
    outputs: ['fileCount', 'summary', 'status'],
    roles: ['coder', 'reviewer'],
    promptName: 'Backend code generator prompt',
    promptSummary: 'Morpheus as backend code generator. Generate production-ready backend code connecting ALL infrastructure components. Include: server entry point, all route handlers, database schema/migrations, auth middleware, config files (package.json, wrangler.toml, docker-compose.yml, Dockerfile, .env.example), README. Match the frontend\'s fetch/axios calls for API contract. No placeholders, no TODOs. Each file fully functional.',
    workflow: [
      'Load project + files',
      'Read backend/.plan.json (must exist — run planning first)',
      'Build codegen hint from components + env vars',
      'Build frontend reference context (for API contract matching)',
      'invokeAI(role=coder) with genSchema → { files, summary }',
      'Reviewer: reviewAndRetry on backend fileOps → checks generated code',
      'Delete existing backend code files (keep .plan.json)',
      'Save new backend files (dedup by normalized path)',
      'Log usage (phase: backend_generate, components, fileCount)',
    ],
    jsonSchemas: [
      { name: 'Generation response', fields: ['files [{ path, content }]', 'summary (string)'] },
    ],
  },
  {
    name: 'deployBackend',
    category: 'Architect (Backend Planning & Deploy)',
    purpose: 'Deploys generated backend code to chosen live infrastructure targets. Handles ALL selected components: API host (live-deploys to Cloudflare Workers; dashboard links for others), database (executes SQL on Supabase via Management API; SQL + editor link for others), auth/storage/cache (code-level integrations with dashboard links). Stores deploy metadata in backend/.deploy.json.',
    inputs: ['projectId', 'components', 'dryRun?'],
    outputs: ['deployResults [{ component, service, status, url? }]', 'deployUrl', 'status'],
    roles: [],
    promptName: 'N/A (infrastructure deployment, no LLM)',
    promptSummary: 'No AI call — pure infrastructure deployment. Reads per-user hosting credentials from UserSettings.connections. Validates credentials (dry-run mode). Deploys to Cloudflare Workers via API, executes SQL on Supabase via Management API, returns dashboard links for Vercel/Netlify/Railway/Render/Fly. Stores deploy metadata for log retrieval.',
    workflow: [
      'Load project + backend files',
      'Dry-run mode: validate credentials + entry point + SQL files → return warnings',
      'Read per-user hosting credentials from UserSettings.connections',
      'For each component: deploy or return dashboard/ZIP/SQL instructions',
      'API host: Cloudflare Workers live deploy; others → ZIP/manual',
      'Database: Supabase SQL execution via Management API; others → SQL + editor link',
      'Auth/Storage/Cache: code-level → dashboard links for verification',
      'Store deploy metadata in backend/.deploy.json',
      'Log usage',
    ],
  },
  {
    name: 'generateTests',
    category: 'AI Code Generation',
    purpose: 'Analyzes the project and generates a complete, production-grade test suite plus CI pipeline. Detects language/framework/test runner from existing files. Generates real test files with actual assertions, edge cases, and a GitHub Actions CI workflow.',
    inputs: ['projectId', 'spec?'],
    outputs: ['reply', 'fileOperations', 'testCount'],
    roles: ['coder', 'reviewer'],
    promptName: 'TESTS_PROMPT',
    promptSummary: 'Morpheus in TEST GENERATION MODE. Detect project language, framework, test runner from package.json/requirements.txt/go.mod/Cargo.toml/etc. Generate REAL test files — actual assertions, real edge cases, no placeholders. Cover core modules: unit tests for key functions, integration tests for interactions. Generate CI config (.github/workflows/ci.yml) appropriate to platform (Node→jest/vitest, Python→pytest, Go→go test, Rust→cargo test, Java→gradlew test, Arduino→pio run). Never delete source files. Extend existing tests, don\'t replace.',
    workflow: [
      'Load project + files',
      'Create snapshot before test generation',
      'Build files context',
      'invokeAI(role=coder) with test schema → { reply, fileOperations, testCount }',
      'Reviewer: reviewAndRetry on test fileOps → checks generated tests',
      'Apply file operations',
      'Save [TESTS] reply to ChatMessage',
      'Log usage (testCount, fileCount)',
    ],
    jsonSchemas: [
      { name: 'Test response', fields: ['reply (string)', 'fileOperations [{ path, content, action: create|update }]', 'testCount (number)'] },
    ],
  },
  {
    name: 'generateNativePrototype',
    category: 'AI Code Generation',
    purpose: 'Generates a rapid native prototype — a self-contained HTML document that serves as a visual mockup of what the native app (Android, iOS, desktop, embedded) would look like when built. Extracts colors, layout, text from source files and simulates logic flow.',
    inputs: ['projectId'],
    outputs: ['html', 'target', 'fileCount'],
    roles: ['planner'],
    promptName: 'Native prototype SYSTEM_PROMPT',
    promptSummary: 'Rapid prototyping engine. Given native app source code, generate a single self-contained HTML document as a VISUAL RAPID PROTOTYPE — web-based mockup showing exact look, feel, layout, colors, and logic flow. Match target platform visual conventions (android→Material, ios→HIG, windows→title bar, mac→traffic lights, etc.). Extract colors and text from source verbatim. Simulate button click handlers. If source is skeletal, infer full UI from project name/description. Must work in iframe sandbox with allow-scripts.',
    workflow: [
      'Load project (must be native target: android-apk, ios-app, windows-exe, mac-app, linux-binary, python-package, rpi-distro, arduino-firmware)',
      'Filter relevant files (skip node_modules, .git, lock files; max 25 files, max 6K chars each)',
      'invokeAI(role=planner) → { html }',
      'Strip markdown fences if LLM added them',
      'Log usage (target, fileCount)',
    ],
    jsonSchemas: [
      { name: 'Prototype response', fields: ['html (string — complete <!DOCTYPE html> document)'] },
    ],
  },
  {
    name: 'generateRebuildDoc',
    category: 'AI Code Generation',
    purpose: 'Generates the comprehensive standalone rebuild blueprint — a complete self-contained document for rebuilding Morpheus without Base44. Fetches live entity schemas, documents all backend functions, frontend structure, integrations, build process, and standalone reconstruction guide. Uploads as file (exceeds entity field limit).',
    inputs: [],
    outputs: ['version', 'contentSize', 'docId', 'updated'],
    roles: [],
    promptName: 'N/A (static document generation, no LLM)',
    promptSummary: 'No AI call — generates a static markdown blueprint from hardcoded registries (ENTITY_NAMES, BACKEND_FUNCTIONS, FRONTEND_PAGES, FRONTEND_COMPONENTS, FRONTEND_HOOKS, SHARED_MODULES) + live entity schemas fetched from the database. Uploads the full content as a file and stores a truncated preview in the RebuildDoc entity.',
    workflow: [
      'Fetch live entity schemas for all 11 entities',
      'Build markdown from registries: purpose, architecture, data model, backend functions, frontend structure, integrations, build process, env vars, standalone reconstruction guide',
      'Upload full content as markdown file via UploadFile',
      'Store truncated preview (2K chars) + file_url in RebuildDoc entity (upsert)',
      'Log usage',
    ],
  },
  {
    name: 'updateDependencies',
    category: 'AI Code Generation',
    purpose: 'Scans project files for package manifests (package.json, requirements.txt, go.mod, Cargo.toml, etc.) and updates dependencies to latest versions. Syncs lockfiles and handles multi-ecosystem projects.',
    inputs: ['projectId'],
    outputs: ['reply', 'fileOperations'],
    roles: ['coder'],
    promptName: 'Dependency update prompt',
    promptSummary: 'Scans for package manifests across ecosystems (npm, pip, go, cargo, gradle, maven, pub, composer, nuget, gem). Updates to latest compatible versions. Syncs lockfiles (package-lock.json, poetry.lock, etc.). Preserves semantic versioning ranges (^, ~, >=). Handles monorepos and multi-ecosystem projects.',
    workflow: [
      'Load project + files',
      'Detect package manifests by extension/filename',
      'invokeAI(role=coder) → updated manifest files',
      'Apply file operations',
      'Log usage',
    ],
  },
];

export const AI_SHARED_MODULES = [
  {
    name: 'aiUtils.ts',
    purpose: 'Shared AI invocation router. Routes to platform InvokeLLM or user-configured custom OpenAI-compatible endpoint. Resolves role-specific model overrides (planner/coder/reviewer/diagnosis). Handles vision content, JSON schema enforcement, and output truncation detection.',
    exports: ['getUserSettings', 'invokeAI', 'InvokeAIResult'],
    keyLogic: [
      'getUserSettings: reads UserSettings entity (latest record) for AI config',
      'invokeAI(base44, prompt, schema?, fileUrls?, role?): routes to platform or custom',
      'Role override: planner_model, coder_model, reviewer_model, diagnosis_model from UserSettings',
      'Custom mode: requires ai_mode=custom + ai_base_url + ai_api_key + ai_model',
      'Custom endpoint: POST {base}/chat/completions with model, messages, temperature=0.7',
      'Vision: image URLs → image_url content parts; other URLs → text reference list',
      'JSON: response_format={type:"json_object"} + schema instruction appended to prompt',
      'Truncation: finish_reason==="length" → throws OUTPUT_TRUNCATED sentinel',
      'No max_tokens cap — full output window for maximum think power',
    ],
    usedBy: ['chatWithMorpheus', 'autonomousBuildStep', 'diagnoseIssue', 'planBackend', 'generateBackend', 'generateTests', 'generateNativePrototype', 'updateDependencies'],
  },
  {
    name: 'reviewer.ts',
    purpose: 'Code review agent — the third phase of the build pipeline. Checks generated file operations for correctness, security, performance, completeness, and UI polish BEFORE commit. If critical issues found, gives the Coder ONE retry pass with review feedback. Never blocks permanently — commits regardless after retry.',
    exports: ['reviewFileOperations', 'formatReviewChatBlock', 'buildRetryPrompt', 'reviewAndRetry', 'ReviewResult', 'ReviewIssue'],
    keyLogic: [
      'REVIEWER_PROMPT: checks CORRECTNESS (syntax, imports, undefined vars), SECURITY (eval, hardcoded secrets, SQL injection), PERFORMANCE (N+1, missing memo, O(n²)), COMPLETENESS (placeholders, TODO, empty bodies), UI POLISH (warning only — never blocks)',
      'reviewFileOperations: invokeAI(role=reviewer) with file ops + context + plan',
      'reviewAndRetry: dedup by path → review → if critical → retry with buildRetryPrompt → re-review',
      'formatReviewChatBlock: critical issues prefixed with CRITICAL: marker for red chat rendering',
      'buildRetryPrompt: lists issues, shows previous file ops, asks for corrected versions',
      'One retry max — never blocks a build permanently, just cleans when it can',
    ],
    usedBy: ['chatWithMorpheus', 'autonomousBuildStep', 'diagnoseIssue', 'generateBackend', 'generateTests'],
  },
  {
    name: 'diagnosis.ts',
    purpose: 'Shared diagnosis utilities for the unified Morpheus diagnosis agent. Categorizes errors (credential vs code-level vs auth), builds LLM fix prompts, and applies file fixes across all issue types (deploy, compile, github, build).',
    exports: ['isCredentialError', 'isAuthError', 'buildCredentialAction', 'applyFileFixes', 'fixResponseSchema', 'Diagnosis', 'AutoFix', 'NeedsAction'],
    keyLogic: [
      'isCredentialError: detects "not configured", "access token not set", "unauthorized + token"',
      'isAuthError: detects "github connection", "not connected", "not authenticated", "401 + github"',
      'buildCredentialAction: structured action item with /settings link and credential steps',
      'applyFileFixes: updates existing or creates new ProjectFile records for each fix',
      'fixResponseSchema: JSON schema for LLM fix responses { fixes: [{ component, issue, fix, files }], summary }',
      'detectLanguage: maps file extensions to language strings for ProjectFile.language',
    ],
    usedBy: ['diagnoseIssue'],
  },
  {
    name: 'designSystem.ts',
    purpose: 'Shared design system for web-app builds. When the project targets web-app, the chat pipeline injects a styles.css with this stylesheet and instructs the coder to build on top of it — so generated apps start polished instead of raw unstyled HTML.',
    exports: ['DESIGN_SYSTEM_CSS', 'designSystemPromptBlock', 'POLISH_PROMPT'],
    keyLogic: [
      'DESIGN_SYSTEM_CSS: framework-agnostic pure CSS with custom properties, light/dark via prefers-color-scheme',
      'designSystemPromptBlock: returns a prompt section telling the coder to use the design tokens',
      'POLISH_PROMPT: second-pass prompt that touches ONLY styling files — refines spacing, transitions, hover/focus states',
      'Tokens: --bg, --surface, --border, --text, --primary, --accent, --danger, --success, --radius, --space, --font, --mono',
    ],
    usedBy: ['chatWithMorpheus'],
  },
];

export const AI_WORKFLOWS = [
  {
    name: 'Chat Build Pipeline',
    trigger: 'Operator sends a message in ChatPanel',
    steps: [
      { actor: 'Frontend', action: 'useWorkspace.sendMessage → base44.functions.invoke("chatWithMorpheus", { projectId, message, fileUrls })' },
      { actor: 'chatWithMorpheus', action: 'Load project + ALL files + ENTIRE conversation history (perpetual memory)' },
      { actor: 'Planner (AI)', action: 'invokeAI(role=planner) → { reply, needsCode, needsClarification, plan }' },
      { actor: 'Clarification Gate', action: 'If needsClarification → save reply, return early (no code written)' },
      { actor: 'Coder (AI)', action: 'invokeAI(role=coder) with plan → { fileOperations: [{ path, content, action }] }' },
      { actor: 'Design System', action: 'If web-app and no styles.css → inject DESIGN_SYSTEM_CSS verbatim' },
      { actor: 'Reviewer (AI)', action: 'reviewAndRetry → invokeAI(role=reviewer) checks correctness/security/performance' },
      { actor: 'Retry Gate', action: 'If critical issues → Coder retry with buildRetryPrompt → re-review' },
      { actor: 'Database', action: 'createSnapshot → applyFileOperations (create/update/delete ProjectFile records)' },
      { actor: 'Polish (AI)', action: 'If project.polish_ui → second coder call touching ONLY styling files' },
      { actor: 'Database', action: 'Save Morpheus reply + review block to ChatMessage; update Project status' },
      { actor: 'Usage', action: 'logUsage with toolchain manifest (planner/coder/reviewer models, provider)' },
    ],
  },
  {
    name: 'Autonomous Build Loop',
    trigger: 'Operator starts autonomous build in AutonomousPanel',
    steps: [
      { actor: 'Frontend', action: 'AutonomousPanel → ws.runAutonomousStep → base44.functions.invoke("autonomousBuildStep", { projectId, spec })' },
      { actor: 'autonomousBuildStep', action: 'Load project + files + history; create snapshot before changes' },
      { actor: 'Planner (AI)', action: 'invokeAI(role=planner) → { assessment, plan, isComplete }' },
      { actor: 'Complete Check', action: 'If isComplete → mark project ready, return (no coder call)' },
      { actor: 'Coder (AI)', action: 'invokeAI(role=coder) with plan → 4-5 files max (output budgeting)' },
      { actor: 'Truncation Handler', action: 'If OUTPUT_TRUNCATED → set truncated=true, no files, panel retries smaller' },
      { actor: 'Reviewer (AI)', action: 'reviewAndRetry → checks + retry on critical issues' },
      { actor: 'Database', action: 'applyFileOperations; update Project status (building/ready)' },
      { actor: 'Frontend', action: 'Panel checks isComplete → if false, loop again; if true, stop' },
    ],
  },
  {
    name: 'Diagnosis & Auto-Fix',
    trigger: 'Build/deploy/compile/github error occurs',
    steps: [
      { actor: 'Frontend', action: 'CompilePanel/BackendPanel catches error → useDiagnosis → base44.functions.invoke("diagnoseIssue", { type, projectId, errorContext })' },
      { actor: 'diagnoseIssue', action: 'Switch on type: deploy | compile | github | build' },
      { actor: 'Classifier', action: 'isCredentialError? → buildCredentialAction (no LLM). isAuthError? → /settings action item' },
      { actor: 'Manual Handler', action: 'ZIP status → download/upload steps. SQL-ready → SQL editor steps' },
      { actor: 'Diagnosis (AI)', action: 'autoFixCodeErrors: invokeAI(role=diagnosis) with error context + file context → { fixes, summary }' },
      { actor: 'Reviewer (AI)', action: 'reviewAndRetry on fix fileOps → checks regenerated files' },
      { actor: 'Database', action: 'applyFileFixes → update/create ProjectFile records with corrected content' },
      { actor: 'Frontend', action: 'DiagnosisPanel shows auto-fixed items + remaining action items → REDEPLOY or ASK MORPHEUS' },
    ],
  },
  {
    name: 'Architect: Plan → Generate → Deploy',
    trigger: 'Operator uses Architect page or BackendPanel',
    steps: [
      { actor: 'Frontend', action: 'Architect/BackendPanel → base44.functions.invoke("planBackend", { projectId })' },
      { actor: 'planBackend (AI)', action: 'invokeAI(role=planner) analyzes frontend files → { summary, database, api, auth, storage, envVars, components }' },
      { actor: 'Validator', action: 'Validate AI-suggested component IDs against known COMPONENTS list (fallback to default)' },
      { actor: 'Database', action: 'Save plan as backend/.plan.json' },
      { actor: 'Frontend', action: 'Operator selects components → base44.functions.invoke("generateBackend", { projectId, components })' },
      { actor: 'generateBackend (AI)', action: 'invokeAI(role=coder) with plan + codegen hint → { files, summary }' },
      { actor: 'Reviewer (AI)', action: 'reviewAndRetry on backend fileOps → checks generated backend code' },
      { actor: 'Database', action: 'Delete old backend files; save new ones with backend/ prefix' },
      { actor: 'Frontend', action: 'Operator clicks DEPLOY → base44.functions.invoke("deployBackend", { projectId, components })' },
      { actor: 'deployBackend', action: 'Read UserSettings.connections → deploy to Cloudflare/Supabase/etc or return ZIP/SQL/manual instructions' },
      { actor: 'Database', action: 'Store deploy metadata in backend/.deploy.json' },
    ],
  },
  {
    name: 'Test Generation',
    trigger: 'Operator clicks TESTS in ProjectBar',
    steps: [
      { actor: 'Frontend', action: 'TestsPanel → base44.functions.invoke("generateTests", { projectId, spec })' },
      { actor: 'generateTests (AI)', action: 'invokeAI(role=coder) with TESTS_PROMPT → detects language/framework/test runner' },
      { actor: 'Coder (AI)', action: 'Generates real test files (assertions, edge cases) + CI workflow (.github/workflows/ci.yml)' },
      { actor: 'Reviewer (AI)', action: 'reviewAndRetry on test fileOps → checks generated tests' },
      { actor: 'Database', action: 'createSnapshot → applyFileOperations; save [TESTS] reply to ChatMessage' },
    ],
  },
  {
    name: 'Native Prototype',
    trigger: 'Operator clicks PREVIEW on a native-target project',
    steps: [
      { actor: 'Frontend', action: 'PreviewPanel → base44.functions.invoke("generateNativePrototype", { projectId })' },
      { actor: 'generateNativePrototype (AI)', action: 'invokeAI(role=planner) with native SYSTEM_PROMPT' },
      { actor: 'Planner (AI)', action: 'Extracts colors/layout/text from source → generates self-contained HTML mockup' },
      { actor: 'Frontend', action: 'Render HTML in iframe sandbox (allow-scripts) — interactive visual prototype' },
    ],
  },
];

export const AI_PIPELINE_SUMMARY = {
  phases: [
    { name: 'Planner', role: 'planner', description: 'High think-power. Reasons about architecture, design, intent. Produces precise build plan. Asks clarification only for genuine build-blocking ambiguity.' },
    { name: 'Coder', role: 'coder', description: 'Fast lightweight. Implements the plan precisely. Full file content, no placeholders. Output budgeting: 4-5 files max per step.' },
    { name: 'Reviewer', role: 'reviewer', description: 'Checks correctness, security, performance, completeness, UI polish. One retry pass on critical issues. Never blocks permanently.' },
    { name: 'Diagnosis', role: 'diagnosis', description: 'Elite debugger. Analyzes errors, regenerates broken files with fixes. Classifies credential vs code-level issues.' },
  ],
  routing: 'invokeAI(base44, prompt, schema?, fileUrls?, role?) → getUserSettings → role model override? → custom endpoint? → platform InvokeLLM or fetch to custom URL',
  guarantees: [
    'Every code-producing function runs through reviewAndRetry — no code commits without a review pass',
    'Output truncation detected via finish_reason==="length" → autonomous loop reduces batch size',
    'Perpetual project memory — entire conversation history loaded every call, not just a window',
    'Full toolchain manifest logged per build (planner/coder/reviewer models + provider)',
    'Design system injected for web-app targets so apps never land with raw unstyled HTML',
    'Credential errors never sent to LLM — classified into structured user action items',
  ],
};