// Morpheus Operations Flow Diagram — live data model.
export const SDK_INFO = {
  sdk: '@base44/sdk@0.8.40',
  runtime: 'base44-deno (Deno)',
  aiProvider: 'platform InvokeLLM | custom OpenAI-compatible endpoint',
  githubConnector: 'NebulaCode GitHub (Per-User) — id 6a8785ad122b26c1461f0f6c',
  stripeMode: 'Live Mode',
};

export const SHARED_MODULES = [
  { name: 'aiUtils.ts', purpose: 'Unified AI invocation — platform InvokeLLM or custom OpenAI-compatible endpoint', exports: ['invokeAI()', 'getUserSettings()'], details: 'Resolves role-specific model overrides (planner/coder/reviewer/diagnosis) from UserSettings. Custom mode supports vision and detects OUTPUT_TRUNCATED via finish_reason=length.', usedBy: ['chatWithMorpheus', 'autonomousBuildStep', 'planBackend', 'generateBackend', 'generateTests', 'diagnoseIssue', 'reviewer.ts'] },
  { name: 'projectUtils.ts', purpose: 'Entity CRUD helpers, snapshot management, usage logging, large-string offload', exports: ['logUsage()', 'detectLanguage()', 'offloadLargeString()', 'readOffloadedString()', 'createSnapshot()', 'applyFileOperations()'], details: 'CREDIT_COSTS map (chat_build=2, autonomous_step=3, etc). createSnapshot offloads >8KB to file storage. applyFileOperations dedupes by path.', usedBy: ['chatWithMorpheus', 'autonomousBuildStep', 'generateTests', 'updateDependencies', 'uploadToGithub', 'importFromGithub', 'publishTemplate', 'installTemplate', 'planBackend', 'generateBackend', 'deployBackend', 'diagnoseIssue'] },
  { name: 'reviewer.ts', purpose: 'Third-phase review agent — checks code before commit, retries on critical issues', exports: ['reviewFileOperations()', 'reviewAndRetry()', 'formatReviewChatBlock()', 'buildRetryPrompt()'], details: 'Reviews correctness, security, performance, completeness, UI polish. Critical issues trigger ONE coder retry. Never blocks permanently.', usedBy: ['chatWithMorpheus', 'autonomousBuildStep', 'generateBackend', 'generateTests', 'diagnoseIssue'] },
  { name: 'githubConnection.ts', purpose: 'Resolves app user GitHub OAuth token via per-user connector', exports: ['getAppUserGithubToken()', 'getAppUserGithubLogin()', 'GITHUB_CONNECTOR_ID'], details: 'Calls base44.asServiceRole.connectors.getCurrentAppUserConnection(connectorId). Throws if GitHub not connected.', usedBy: ['compileProject', 'getCompileStatus', 'uploadToGithub', 'importFromGithub', 'deployBackend', 'checkGithubConnection'] },
  { name: 'githubPush.ts', purpose: 'GitHub Git Data API — create repos, push files, set encrypted secrets', exports: ['ghHeaders()', 'ghJson()', 'createRepo()', 'pushFiles()', 'encryptAndSetGithubSecret()'], details: 'pushFiles uses base_tree to preserve existing files, retries on 404. encryptAndSetGithubSecret uses libsodium NaCl sealed box.', usedBy: ['compileProject', 'uploadToGithub', 'importFromGithub', 'deployBackend', 'getCompileStatus', 'githubConnection.ts'] },
  { name: 'infrastructureComponents.ts', purpose: 'Infrastructure component registry — service options, codegen hints, deploy credentials', exports: ['COMPONENTS', 'getServiceOption()', 'DEFAULT_COMPONENTS', 'buildCodegenPrompt()', 'buildEnvVars()', 'getDashboardUrl()', 'validateDeployCredentials()'], details: 'Defines api_host (Cloudflare/Vercel/Netlify/Railway/Render/Fly), database (Supabase/Neon/Turso/PlanetScale), auth, file_storage, cache.', usedBy: ['planBackend', 'generateBackend', 'deployBackend', 'diagnoseIssue'] },
  { name: 'stripeUtils.ts', purpose: 'Stripe API wrapper — authenticated fetch, form encoding, revenue split', exports: ['stripeFetch()', 'encodeForm()', 'getStripeKey()', 'computeSplit()', 'PLATFORM_COMMISSION'], details: 'stripeFetch reads STRIPE_SECRET_KEY, sends Bearer auth + Stripe-Version 2025-10-29.clover. computeSplit: 80% seller / 20% platform.', usedBy: ['publishTemplate', 'createTemplateCheckout', 'stripeWebhook'] },
  { name: 'diagnosis.ts', purpose: 'Error categorization and file-fix application for diagnosis agent', exports: ['isCredentialError()', 'isAuthError()', 'buildCredentialAction()', 'applyFileFixes()', 'fixResponseSchema'], details: 'Classifies errors as credential vs code-level. applyFileFixes regenerates broken files with LLM fixes.', usedBy: ['diagnoseIssue'] },
  { name: 'toolchain.ts', purpose: 'Records exact SDK, runtime, and AI models that produced each build output', exports: ['buildToolchain()', 'parseToolchain()', 'SDK_VERSION', 'RUNTIME', 'CLIENT_TOOLS'], details: 'Toolchain manifest stored in UsageRecord.metadata, flows into BUILD_LOG.md. Lets operators trace any output to its toolchain.', usedBy: ['chatWithMorpheus', 'autonomousBuildStep', 'buildLogs.ts'] },
  { name: 'healthCheck.ts', purpose: 'Post-deploy health verification with retry logic', exports: ['checkHealth()', 'withRetry()'], details: 'checkHealth pings URLs with timeout+retries. withRetry wraps deploy functions — retries on error status.', usedBy: ['deployBackend', 'checkDeployHealth'] },
  { name: 'buildLogs.ts', purpose: 'Aggregates build log data from ChatMessage, FileSnapshot, UsageRecord', exports: ['aggregateBuildLogs()', 'generateBuildLogMarkdown()'], details: 'Merges chat, snapshots, usage into chronological log. Parses toolchain manifest. Generates BUILD_LOG.md for repos.', usedBy: ['uploadToGithub', 'getBuildLogs'] },
  { name: 'designSystem.ts', purpose: 'Shared design system CSS + UI polish prompt for web-app targets', exports: ['designSystemPromptBlock()', 'POLISH_PROMPT', 'DESIGN_SYSTEM_CSS'], details: 'Injected into chatWithMorpheus for web-app targets. POLISH_PROMPT drives optional UI polish pass.', usedBy: ['chatWithMorpheus'] },
  { name: 'compile-targets/index.ts', purpose: 'Compile target adapter registry', exports: ['getCompileTarget()', 'listCompileTargets()'], details: 'Each adapter (android-apk, web-app, windows-exe, etc) handles validate, scaffold, buildSteps, runner, artifact, errorPatterns.', usedBy: ['compileProject', 'getCompileStatus'] },
  { name: 'workflow-renderer.ts', purpose: 'Renders build steps into GitHub Actions workflow YAML', exports: ['renderWorkflow()'], details: 'Takes runner, steps, artifact — produces .github/workflows/build.yml.', usedBy: ['compileProject'] },
];

export const OPERATIONS = [
  { name: 'chatWithMorpheus', category: 'AI Build', purpose: 'Two-phase conversational build — Planner reasons, Coder implements, Reviewer checks, optional UI polish', inputs: ['projectId', 'message', 'fileUrls?'], outputs: ['reply', 'fileOperations[]', 'needsClarification'], calls: ['base44.auth.me()', 'Project.get + ProjectFile.filter + ChatMessage.filter (perpetual memory)', 'ChatMessage.create (user + morpheus)', 'invokeAI(planner) — reason + plan', 'invokeAI(coder) — implement plan', 'reviewAndRetry() — review before commit', 'invokeAI(coder) — UI polish (if polish_ui)', 'createSnapshot() + applyFileOperations()', 'Project.update({status}) + logUsage("chat_build")', 'buildToolchain() — record models'], entities: ['Project', 'ProjectFile', 'ChatMessage', 'UsageRecord', 'FileSnapshot'], sharedModules: ['aiUtils.ts', 'projectUtils.ts', 'reviewer.ts', 'toolchain.ts', 'designSystem.ts'] },
  { name: 'autonomousBuildStep', category: 'AI Build', purpose: 'Autonomous multi-step build loop — Planner assesses, Coder writes 4-5 files/step, Reviewer checks', inputs: ['projectId', 'spec?'], outputs: ['reply', 'fileOperations[]', 'isComplete', 'truncated', 'reviewStatus', 'outputMetrics'], calls: ['Project.get + ProjectFile.filter + ChatMessage.filter', 'createSnapshot() — pre-step', 'invokeAI(planner) — assess + plan (THIS STEP vs NEXT STEPS)', 'invokeAI(coder) — implement 4-5 files max', 'reviewAndRetry() — review + retry', 'applyFileOperations() — commit', 'ChatMessage.create ([AUTONOMOUS] reply)', 'Project.update({status}) + logUsage("autonomous_step")', 'measureFileOps() — token/char metrics'], entities: ['Project', 'ProjectFile', 'ChatMessage', 'UsageRecord', 'FileSnapshot'], sharedModules: ['aiUtils.ts', 'projectUtils.ts', 'reviewer.ts', 'toolchain.ts'] },
  { name: 'compileProject', category: 'Compile', purpose: 'Compiles project to native artifact via GitHub Actions — validates, scaffolds, pushes, triggers workflow', inputs: ['projectId', 'dryRun?'], outputs: ['repoFullName', 'repoUrl', 'target', 'status: dispatched'], calls: ['Project.get + ProjectFile.filter', 'getCompileTarget(target) — load adapter', 'adapter.requiredSecrets — check env', 'adapter.validate() + adapter.scaffold() + adapter.buildSteps()', 'renderWorkflow(runner, steps, artifact) — YAML', 'getAppUserGithubToken()', 'createRepo() + pushFiles(project + workflow)', 'GitHub API: /actions/workflows — find ID (8 retries)', 'GitHub API: /dispatches — trigger build', 'logUsage("compile")'], entities: ['Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['compile-targets/index.ts', 'workflow-renderer.ts', 'githubConnection.ts', 'githubPush.ts', 'projectUtils.ts'], externalServices: ['GitHub API (repos, git/trees, actions/workflows, dispatches)'] },
  { name: 'getCompileStatus', category: 'Compile', purpose: 'Polls GitHub Actions run status, step progress, failed job logs, and release artifacts', inputs: ['repoFullName', 'target?'], outputs: ['status', 'conclusion', 'runUrl', 'stepProgress', 'logs[]', 'releaseUrl', 'assets[]'], calls: ['getAppUserGithubToken()', 'getCompileTarget(target) — errorPatterns', 'GitHub API: /actions/runs — latest run', 'GitHub API: /actions/runs/{id}/jobs — step progress', 'GitHub API: /actions/jobs/{id}/logs — failed logs', 'extractErrorContext(log, errorPatterns)', 'GitHub API: /releases/latest — artifacts (4 retries)'], entities: [], sharedModules: ['githubConnection.ts', 'githubPush.ts', 'compile-targets/index.ts'], externalServices: ['GitHub API (actions/runs, jobs, logs, releases)'] },
  { name: 'saveCompiledArtifacts', category: 'Compile', purpose: 'Downloads compiled artifacts from GitHub releases and stores them', inputs: ['projectId', 'repoFullName', 'assets'], outputs: ['savedArtifacts[]'], calls: ['getAppUserGithubToken()', 'GitHub API: download release assets', 'UploadFile() — store artifacts'], entities: ['Project'], sharedModules: ['githubConnection.ts'], externalServices: ['GitHub API (releases/assets)'] },
  { name: 'planBackend', category: 'Backend', purpose: 'Analyzes frontend and generates backend architecture plan (DB schema, API routes, auth, storage, env vars)', inputs: ['projectId'], outputs: ['plan', 'status: planned'], calls: ['Project.get + ProjectFile.filter', 'invokeAI(planner) — architecture analysis', 'COMPONENTS — infrastructure options', 'getServiceOption() — validate AI suggestions', 'ProjectFile.create/update — save backend/.plan.json', 'logUsage("autonomous_step", {phase: backend_plan})'], entities: ['Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['aiUtils.ts', 'projectUtils.ts', 'infrastructureComponents.ts'] },
  { name: 'generateBackend', category: 'Backend', purpose: 'Generates production-ready backend code from architecture plan and chosen components', inputs: ['projectId', 'components'], outputs: ['fileCount', 'summary', 'status: generated'], calls: ['Project.get + ProjectFile.filter', 'buildCodegenPrompt(components) + buildEnvVars(components)', 'invokeAI(coder) — generate backend files', 'reviewAndRetry() — review', 'ProjectFile.delete (old) + bulkCreate (new backend/ files)', 'logUsage("autonomous_step", {phase: backend_generate})'], entities: ['Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['aiUtils.ts', 'projectUtils.ts', 'reviewer.ts', 'infrastructureComponents.ts'] },
  { name: 'deployBackend', category: 'Backend', purpose: 'Deploys backend to live targets — Cloudflare/Vercel/Netlify direct, Railway/Render/Fly via GitHub, Supabase SQL', inputs: ['projectId', 'components', 'dryRun?'], outputs: ['results[]', 'deployInfo'], calls: ['Project.get + ProjectFile.filter', 'UserSettings.filter — credentials', 'BackendConfig.filter — domain + API keys', 'deployApiHost() → Cloudflare/Vercel/Netlify (direct) or Railway/Render/Fly (via GitHub)', 'deployDatabase() → Supabase Management API (SQL exec) or SQL+link', 'withRetry() — auto-retry on error', 'fetch(url) — post-deploy health check', 'applyBackendConfig() — API keys + custom domain', 'ProjectFile.create — save backend/.deploy.json', 'logUsage("compile", {phase: backend_deploy})'], entities: ['Project', 'ProjectFile', 'UserSettings', 'BackendConfig', 'UsageRecord'], sharedModules: ['infrastructureComponents.ts', 'projectUtils.ts', 'githubConnection.ts', 'githubPush.ts', 'healthCheck.ts'], externalServices: ['Cloudflare API', 'Vercel API', 'Netlify API', 'Railway GraphQL', 'Render API', 'Fly.io (GitHub Actions)', 'Supabase Management API'] },
  { name: 'wireFrontendToBackend', category: 'Backend', purpose: 'Updates frontend API calls to point to deployed backend URL', inputs: ['projectId', 'backendUrl'], outputs: ['updatedFiles[]'], calls: ['Project.get + ProjectFile.filter', 'invokeAI() — rewrite fetch/axios URLs', 'applyFileOperations()'], entities: ['Project', 'ProjectFile'], sharedModules: ['aiUtils.ts', 'projectUtils.ts'] },
  { name: 'checkDeployHealth', category: 'Backend', purpose: 'Health-checks deployed backend URLs and returns status', inputs: ['urls[]'], outputs: ['results[]'], calls: ['checkHealth(url) — ping with retries'], entities: [], sharedModules: ['healthCheck.ts'] },
  { name: 'getBackendLogs', category: 'Backend', purpose: 'Retrieves backend deployment and runtime logs', inputs: ['projectId'], outputs: ['logs'], calls: ['ProjectFile.filter — find .deploy.json', 'fetch(deployedUrl/logs) — runtime logs'], entities: ['ProjectFile'], sharedModules: [] },
  { name: 'manageBackendConfig', category: 'Backend', purpose: 'Manages backend custom domain and API keys', inputs: ['projectId', 'action', 'data'], outputs: ['config'], calls: ['BackendConfig.filter/create/update', 'crypto.subtle.digest() — hash API keys'], entities: ['BackendConfig'], sharedModules: [] },
  { name: 'diagnoseIssue', category: 'Diagnosis', purpose: 'Unified diagnosis agent — analyzes errors (deploy/compile/github/build), auto-fixes code, returns action plan', inputs: ['type', 'projectId', 'errorContext', 'components?'], outputs: ['diagnosis {summary, autoFixed[], needsUserAction[], allClear}'], calls: ['Project.get + ProjectFile.filter', 'switch(type): diagnoseDeploy|Compile|Github|Build', 'isCredentialError() / isAuthError() — classify', 'buildCredentialAction() — user action plan', 'autoFixCodeErrors() → invokeAI(diagnosis) + reviewAndRetry() + applyFileFixes()', 'logUsage("diagnosis")'], entities: ['Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['aiUtils.ts', 'projectUtils.ts', 'diagnosis.ts', 'reviewer.ts', 'infrastructureComponents.ts'] },
  { name: 'uploadToGithub', category: 'GitHub', purpose: 'Uploads project files + BUILD_LOG.md to a new or existing GitHub repo', inputs: ['projectId', 'repoName', 'isPrivate?'], outputs: ['repoUrl', 'fileCount'], calls: ['getAppUserGithubToken()', 'createRepo()', 'ProjectFile.filter + Project.get', 'aggregateBuildLogs() + generateBuildLogMarkdown()', 'pushFiles(project + BUILD_LOG.md)', 'logUsage("github_upload")'], entities: ['Project', 'ProjectFile', 'UsageRecord', 'ChatMessage', 'FileSnapshot'], sharedModules: ['githubConnection.ts', 'githubPush.ts', 'projectUtils.ts', 'buildLogs.ts'], externalServices: ['GitHub API (repos, git/trees, commits, refs)'] },
  { name: 'importFromGithub', category: 'GitHub', purpose: 'Imports an existing GitHub repo — fetches file tree, downloads blobs, creates project', inputs: ['repoInput', 'compileTarget?'], outputs: ['projectId', 'projectName', 'fileCount', 'truncated'], calls: ['getAppUserGithubToken()', 'GitHub API: /repos/{owner}/{repo}', 'GitHub API: /git/trees/{branch}?recursive=1', 'GitHub API: /git/blobs/{sha} — base64 decode', 'Project.create + ProjectFile.bulkCreate (max 150)', 'ChatMessage.create + logUsage("github_import")'], entities: ['Project', 'ProjectFile', 'ChatMessage', 'UsageRecord'], sharedModules: ['githubConnection.ts', 'githubPush.ts', 'projectUtils.ts'], externalServices: ['GitHub API (repos, git/trees, git/blobs)'] },
  { name: 'checkGithubConnection', category: 'GitHub', purpose: 'Checks if current user has a connected GitHub account', inputs: [], outputs: ['connected', 'login?'], calls: ['getAppUserGithubLogin(base44)'], entities: [], sharedModules: ['githubConnection.ts', 'githubPush.ts'] },
  { name: 'generateTests', category: 'Quality', purpose: 'Generates complete test suite + CI pipeline from project files', inputs: ['projectId', 'spec?'], outputs: ['reply', 'fileOperations[]', 'testCount'], calls: ['Project.get + ProjectFile.filter', 'createSnapshot() — pre-test', 'invokeAI(coder) — generate tests + CI config', 'reviewAndRetry() — review tests', 'applyFileOperations() — commit', 'ChatMessage.create ([TESTS]) + logUsage("test_generation")'], entities: ['Project', 'ProjectFile', 'ChatMessage', 'UsageRecord', 'FileSnapshot'], sharedModules: ['aiUtils.ts', 'projectUtils.ts', 'reviewer.ts'] },
  { name: 'updateDependencies', category: 'Quality', purpose: 'Syncs all dependency manifests to latest versions across 8 ecosystems', inputs: ['projectId'], outputs: ['reply', 'fileOperations[]', 'updatedCount', 'updates[]'], calls: ['Project.get + ProjectFile.filter', 'createSnapshot() — pre-sync', 'REGISTRY updaters — match manifest files', 'lookup(ecosystem, name) — registry API calls:', '  npm→registry.npmjs.org, pypi→pypi.org, maven→repo1.maven.org+dl.google.com', '  cargo→crates.io, go→proxy.golang.org, gem→rubygems.org', '  composer→packagist.org, platformio→registry.platformio.org', 'ProjectFile.update() — write new versions', 'logUsage("chat_simple", {action: sync_deps})'], entities: ['Project', 'ProjectFile', 'UsageRecord', 'FileSnapshot'], sharedModules: ['projectUtils.ts'], externalServices: ['npm registry', 'PyPI', 'Maven Central', 'Google Maven', 'crates.io', 'Go proxy', 'RubyGems', 'Packagist', 'PlatformIO registry'] },
  { name: 'publishTemplate', category: 'Marketplace', purpose: 'Publishes project as marketplace template — creates Stripe product+price for paid templates', inputs: ['projectId', 'tags?', 'category?', 'price', 'screenshots?', 'icon?', 'long_description?'], outputs: ['templateId', 'name', 'fileCount', 'price'], calls: ['Project.get + ProjectFile.filter', 'Template.create (files as JSON)', 'stripeFetch("/products") — create product (if paid)', 'stripeFetch("/prices") — create price (if paid)', 'Template.update({stripe_price_id})', 'logUsage("template_publish")'], entities: ['Project', 'ProjectFile', 'Template', 'UsageRecord'], sharedModules: ['projectUtils.ts', 'stripeUtils.ts'], externalServices: ['Stripe API (products, prices)'] },
  { name: 'createTemplateCheckout', category: 'Marketplace', purpose: 'Creates Stripe Checkout session for purchasing a paid template', inputs: ['templateId', 'buyerId?', 'buyerEmail?', 'successUrl', 'cancelUrl'], outputs: ['url'], calls: ['Template.get(templateId)', 'ensurePriceId() — self-heal stale price IDs', 'stripeFetch("/checkout/sessions") — create session'], entities: ['Template'], sharedModules: ['stripeUtils.ts'], externalServices: ['Stripe API (prices, checkout/sessions)'] },
  { name: 'installTemplate', category: 'Marketplace', purpose: 'Installs template into new project — verifies purchase for paid templates', inputs: ['templateId', 'projectName?'], outputs: ['projectId', 'projectName', 'fileCount'], calls: ['Template.get(templateId)', 'Purchase.filter({template_id, buyer_id, status: paid}) — verify', 'Project.create + ProjectFile.bulkCreate — clone files', 'Template.update({install_count: +1}) (service role)', 'logUsage("template_install")'], entities: ['Template', 'Purchase', 'Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['projectUtils.ts'] },
  { name: 'downloadTemplate', category: 'Marketplace', purpose: 'Downloads template files as ZIP — verifies purchase for paid templates', inputs: ['templateId'], outputs: ['zipUrl'], calls: ['Template.get + Purchase.filter — verify', 'UploadFile() — upload ZIP'], entities: ['Template', 'Purchase'], sharedModules: [] },
  { name: 'stripeWebhook', category: 'Marketplace', purpose: 'Stripe webhook handler — verifies signature, records purchase with 80/20 split', inputs: ['rawBody', 'stripe-signature header'], outputs: ['received: true'], calls: ['secrets.get("STRIPE_WEBHOOK_SECRET")', 'verifyStripeSignature() — HMAC-SHA256', 'computeSplit(amount) — 80% seller / 20% platform', 'Purchase.filter (idempotency) + Purchase.create'], entities: ['Purchase'], sharedModules: ['stripeUtils.ts'], externalServices: ['Stripe (webhook events)'] },
  { name: 'browseTemplates', category: 'Marketplace', purpose: 'Lists marketplace templates with search and category filtering', inputs: ['search?', 'category?'], outputs: ['templates[]'], calls: ['Template.filter() — public read'], entities: ['Template'], sharedModules: [] },
  { name: 'getPublicTemplate', category: 'Marketplace', purpose: 'Fetches single template for public store detail page', inputs: ['templateId'], outputs: ['template'], calls: ['Template.get(templateId)'], entities: ['Template'], sharedModules: [] },
  { name: 'getSellerStats', category: 'Marketplace', purpose: 'Returns seller earnings and sales statistics', inputs: [], outputs: ['totalEarnings', 'totalSales', 'templates[]'], calls: ['Template.filter({author_id}) + Purchase.filter({seller_id, status: paid})'], entities: ['Template', 'Purchase'], sharedModules: ['stripeUtils.ts'] },
  { name: 'getUsageStats', category: 'Utility', purpose: 'Returns credit usage statistics for current user', inputs: [], outputs: ['totalCredits', 'byAction[]', 'recent[]'], calls: ['UsageRecord.filter({created_by_id})'], entities: ['UsageRecord'], sharedModules: [] },
  { name: 'getBuildLogs', category: 'Utility', purpose: 'Returns aggregated build logs for a project', inputs: ['projectId'], outputs: ['logs[]'], calls: ['aggregateBuildLogs(base44, projectId)'], entities: ['ChatMessage', 'FileSnapshot', 'UsageRecord'], sharedModules: ['buildLogs.ts', 'toolchain.ts'] },
  { name: 'restoreSnapshot', category: 'Utility', purpose: 'Restores project files from a saved snapshot', inputs: ['projectId', 'snapshotId'], outputs: ['restoredCount'], calls: ['FileSnapshot.get(snapshotId)', 'readOffloadedString() — fetch if offloaded', 'ProjectFile.delete (current) + bulkCreate (snapshot)'], entities: ['FileSnapshot', 'ProjectFile'], sharedModules: ['projectUtils.ts'] },
  { name: 'generateMorpheusSpeech', category: 'Utility', purpose: 'Generates TTS speech — routes through user-configured engine', inputs: ['text', 'voice?'], outputs: ['audioUrl'], calls: ['UserSettings.filter — TTS config', 'ElevenLabs API / OpenAI TTS API / Custom endpoint', 'GenerateSpeech() — platform fallback'], entities: ['UserSettings'], sharedModules: [], externalServices: ['ElevenLabs API', 'OpenAI TTS API', 'Custom TTS endpoint'] },
  { name: 'emailProjectFiles', category: 'Utility', purpose: 'Emails project files as a ZIP attachment', inputs: ['projectId', 'email'], outputs: ['sent: true'], calls: ['Project.get + ProjectFile.filter', 'UploadFile() — upload ZIP', 'SendEmail() — send with attachment', 'logUsage("email_export")'], entities: ['Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['projectUtils.ts'] },
  { name: 'generateRebuildDoc', category: 'Utility', purpose: 'Generates a rebuild blueprint document for the project', inputs: ['projectId'], outputs: ['docId', 'version', 'file_url'], calls: ['Project.get + ProjectFile.filter', 'invokeAI() — generate blueprint markdown', 'UploadFile() — store full doc', 'RebuildDoc.create — metadata + preview'], entities: ['Project', 'ProjectFile', 'RebuildDoc'], sharedModules: ['aiUtils.ts', 'projectUtils.ts'] },
  { name: 'generateNativePrototype', category: 'Utility', purpose: 'Generates a native prototype preview for a compile target', inputs: ['projectId', 'target'], outputs: ['prototype'], calls: ['Project.get + ProjectFile.filter', 'invokeAI() — generate prototype', 'logUsage("native_prototype")'], entities: ['Project', 'ProjectFile', 'UsageRecord'], sharedModules: ['aiUtils.ts', 'projectUtils.ts'] },
  { name: 'deleteAccount', category: 'Utility', purpose: 'Deletes current user account and all associated data', inputs: [], outputs: ['deleted: true'], calls: ['Project.deleteMany + ProjectFile.deleteMany + ChatMessage.deleteMany', 'UserSettings.deleteMany + UsageRecord.deleteMany + FileSnapshot.deleteMany'], entities: ['Project', 'ProjectFile', 'ChatMessage', 'UserSettings', 'UsageRecord', 'FileSnapshot'], sharedModules: [] },
];

export const WORKFLOWS = [
  { name: 'Conversational Build', trigger: 'Operator sends a message in ChatPanel', steps: [
    { actor: 'ChatPanel.jsx', action: 'sendMessage(projectId, message, fileUrls)' },
    { actor: 'chatWithMorpheus', action: 'Load Project + ProjectFile[] + ChatMessage[] (perpetual memory)' },
    { actor: 'chatWithMorpheus', action: 'Save user message to ChatMessage' },
    { actor: 'invokeAI (planner)', action: 'Reason about intent → {reply, needsCode, needsClarification, plan}' },
    { actor: 'chatWithMorpheus', action: 'If needsClarification → save reply, return (no code)' },
    { actor: 'invokeAI (coder)', action: 'Implement plan → fileOperations[]' },
    { actor: 'reviewer.ts', action: 'reviewAndRetry() — check critical issues, retry once if needed' },
    { actor: 'projectUtils.ts', action: 'createSnapshot() — pre-build file snapshot' },
    { actor: 'projectUtils.ts', action: 'applyFileOperations() — commit create/update/delete' },
    { actor: 'invokeAI (coder)', action: 'If polish_ui + web files → UI polish pass (styling only)' },
    { actor: 'chatWithMorpheus', action: 'Save Morpheus reply + review block to ChatMessage' },
    { actor: 'chatWithMorpheus', action: 'Project.update({status: building}) + logUsage("chat_build")' },
    { actor: 'ChatPanel.jsx', action: 'Render reply + file operations in chat UI' },
  ]},
  { name: 'Autonomous Build Loop', trigger: 'Operator clicks START in AutonomousPanel', steps: [
    { actor: 'AutonomousPanel.jsx', action: 'handleStart() — loop until isComplete or stop' },
    { actor: 'autonomousBuildStep', action: 'Load Project + ProjectFile[] + ChatMessage[]' },
    { actor: 'projectUtils.ts', action: 'createSnapshot() — pre-step snapshot' },
    { actor: 'invokeAI (planner)', action: 'Assess completeness → {assessment, plan, isComplete}' },
    { actor: 'autonomousBuildStep', action: 'If isComplete → Project.update({status: ready}), return' },
    { actor: 'invokeAI (coder)', action: 'Implement 4-5 files max → {fileOperations, isComplete}' },
    { actor: 'reviewer.ts', action: 'reviewAndRetry() — review + retry on critical issues' },
    { actor: 'projectUtils.ts', action: 'applyFileOperations() — commit files' },
    { actor: 'autonomousBuildStep', action: 'Save [AUTONOMOUS] reply to ChatMessage' },
    { actor: 'autonomousBuildStep', action: 'Project.update({status}) + logUsage("autonomous_step")' },
    { actor: 'AutonomousPanel.jsx', action: 'If truncated → reduce batch. If !isComplete → loop.' },
  ]},
  { name: 'Native Compile (GitHub Actions)', trigger: 'Operator clicks COMPILE in CompilePanel', steps: [
    { actor: 'CompilePanel.jsx', action: 'onCompile(projectId, dryRun?)' },
    { actor: 'compileProject', action: 'Load Project + ProjectFile[]' },
    { actor: 'compile-targets', action: 'getCompileTarget(target) — load adapter' },
    { actor: 'adapter', action: 'Check requiredSecrets → validate() → scaffold() → buildSteps()' },
    { actor: 'workflow-renderer', action: 'renderWorkflow(runner, steps, artifact) → build.yml' },
    { actor: 'githubConnection', action: 'getAppUserGithubToken() — resolve OAuth token' },
    { actor: 'githubPush', action: 'createRepo() + pushFiles(project + workflow YAML)' },
    { actor: 'GitHub API', action: 'Wait for workflow registration → find ID (8 retries)' },
    { actor: 'GitHub API', action: 'dispatches — trigger workflow run' },
    { actor: 'CompilePanel.jsx', action: 'Poll getCompileStatus(repoFullName, target) every 5s' },
    { actor: 'getCompileStatus', action: 'GitHub API: /actions/runs → status + conclusion' },
    { actor: 'getCompileStatus', action: 'If in_progress: /actions/runs/{id}/jobs → step progress' },
    { actor: 'getCompileStatus', action: 'If failed: /actions/jobs/{id}/logs → extractErrorContext()' },
    { actor: 'getCompileStatus', action: 'If success: /releases/latest → download assets (4 retries)' },
    { actor: 'CompilePanel.jsx', action: 'If success → saveCompiledArtifacts. If failed → diagnoseIssue.' },
  ]},
  { name: 'Backend Architecture to Deploy', trigger: 'Operator uses Architect page or BackendPanel', steps: [
    { actor: 'Architect/BackendPanel', action: 'Trigger backend pipeline' },
    { actor: 'planBackend', action: 'Load frontend files → invokeAI(planner) → architecture plan' },
    { actor: 'infrastructureComponents', action: 'Validate AI component suggestions against COMPONENTS registry' },
    { actor: 'planBackend', action: 'Save plan to backend/.plan.json (ProjectFile)' },
    { actor: 'generateBackend', action: 'Load plan + components → invokeAI(coder) → backend code' },
    { actor: 'reviewer.ts', action: 'reviewAndRetry() — review backend code' },
    { actor: 'generateBackend', action: 'Delete old → bulkCreate new backend/ files' },
    { actor: 'deployBackend', action: 'Load UserSettings (creds) + BackendConfig (domain/keys)' },
    { actor: 'deployBackend', action: 'deployApiHost() → route to service deployer' },
    { actor: 'Cloudflare/Vercel/Netlify', action: 'Direct API deploy (file upload + deployment)' },
    { actor: 'Railway/Render/Fly', action: 'pushBackendToGithub() → platform API (create service)' },
    { actor: 'deployBackend', action: 'deployDatabase() → Supabase SQL exec or SQL+link' },
    { actor: 'healthCheck', action: 'fetch(url) — post-deploy health ping' },
    { actor: 'deployBackend', action: 'applyBackendConfig() — API keys + custom domain' },
    { actor: 'deployBackend', action: 'Save backend/.deploy.json + logUsage("compile")' },
    { actor: 'wireFrontendToBackend', action: 'Update frontend fetch/axios URLs to backend URL' },
  ]},
  { name: 'AI Diagnosis and Auto-Fix', trigger: 'Compile/deploy/build failure → operator clicks AI DIAGNOSE', steps: [
    { actor: 'CompilePanel/BackendPanel', action: 'diagnoseIssue(type, projectId, errorContext)' },
    { actor: 'diagnoseIssue', action: 'Load Project + ProjectFile[]' },
    { actor: 'diagnoseIssue', action: 'switch(type): deploy | compile | github | build' },
    { actor: 'diagnosis.ts', action: 'isCredentialError() / isAuthError() — classify error' },
    { actor: 'diagnosis.ts', action: 'If credential gap → buildCredentialAction() (user plan)' },
    { actor: 'diagnosis.ts', action: 'If code error → autoFixCodeErrors()' },
    { actor: 'invokeAI (diagnosis)', action: 'Analyze error + regenerate broken files' },
    { actor: 'reviewer.ts', action: 'reviewAndRetry() — review fix files' },
    { actor: 'diagnosis.ts', action: 'applyFileFixes() — commit fixed files' },
    { actor: 'diagnoseIssue', action: 'Return {summary, autoFixed[], needsUserAction[], allClear}' },
    { actor: 'CompilePanel/BackendPanel', action: 'If allClear → retry. If not → show action plan.' },
  ]},
  { name: 'Marketplace: Publish to Purchase to Install', trigger: 'Operator publishes template; buyer purchases and installs', steps: [
    { actor: 'SellerPanel.jsx', action: 'publishTemplate(projectId, tags, price, ...)' },
    { actor: 'publishTemplate', action: 'Load Project + ProjectFile[] → Template.create (files JSON)' },
    { actor: 'stripeUtils.ts', action: 'If price > 0: stripeFetch("/products") + stripeFetch("/prices")' },
    { actor: 'publishTemplate', action: 'Template.update({stripe_price_id}) + logUsage' },
    { actor: 'StoreItem.jsx', action: 'Buyer clicks BUY → createTemplateCheckout(templateId, ...)' },
    { actor: 'createTemplateCheckout', action: 'Template.get → ensurePriceId() (self-heal)' },
    { actor: 'stripeUtils.ts', action: 'stripeFetch("/checkout/sessions") → Stripe Checkout URL' },
    { actor: 'Stripe', action: 'Buyer pays → checkout.session.completed → stripeWebhook' },
    { actor: 'stripeWebhook', action: 'verifyStripeSignature() — HMAC-SHA256' },
    { actor: 'stripeUtils.ts', action: 'computeSplit(amount) — 80% seller / 20% platform' },
    { actor: 'stripeWebhook', action: 'Purchase.filter (idempotency) → Purchase.create' },
    { actor: 'StoreItem.jsx', action: 'Buyer clicks INSTALL → installTemplate(templateId)' },
    { actor: 'installTemplate', action: 'Verify Purchase → Project.create → ProjectFile.bulkCreate' },
    { actor: 'installTemplate', action: 'Template.update({install_count: +1}) + logUsage' },
  ]},
  { name: 'GitHub Import / Export', trigger: 'Operator imports a repo or exports to GitHub', steps: [
    { actor: 'ImportGithubDialog', action: 'importFromGithub(repoInput, target)' },
    { actor: 'importFromGithub', action: 'Parse owner/repo → GitHub API: /repos + /git/trees' },
    { actor: 'importFromGithub', action: 'Filter blobs → fetch /git/blobs/{sha} (base64 decode)' },
    { actor: 'importFromGithub', action: 'Project.create → ProjectFile.bulkCreate (max 150)' },
    { actor: 'ShareDialog', action: 'uploadToGithub(projectId, repoName, isPrivate)' },
    { actor: 'uploadToGithub', action: 'getAppUserGithubToken → createRepo' },
    { actor: 'uploadToGithub', action: 'aggregateBuildLogs() → generateBuildLogMarkdown()' },
    { actor: 'githubPush.ts', action: 'pushFiles(project + BUILD_LOG.md) → Git Data API' },
    { actor: 'uploadToGithub', action: 'logUsage("github_upload") → return repoUrl' },
  ]},
  { name: 'Dependency Sync', trigger: 'Operator clicks SYNC DEPS in ProjectBar', steps: [
    { actor: 'ProjectBar.jsx', action: 'updateDependencies(projectId)' },
    { actor: 'updateDependencies', action: 'Load Project + ProjectFile[] → createSnapshot()' },
    { actor: 'updateDependencies', action: 'For each file: match against REGISTRY updaters' },
    { actor: 'REGISTRY', action: 'Match manifest (package.json, requirements.txt, pom.xml, etc)' },
    { actor: 'lookup()', action: 'Fetch latest from registry API (npm/pypi/maven/cargo/go/gem/composer/platformio)' },
    { actor: 'updateDependencies', action: 'ProjectFile.update() with new versions → logUsage' },
    { actor: 'ProjectBar.jsx', action: 'Show update summary (breaking changes flagged)' },
  ]},
];

export const ENTITIES = [
  { name: 'Project', purpose: 'Frontend/backend project metadata (name, status, compile_target, project_type, polish_ui)' },
  { name: 'ProjectFile', purpose: 'Individual source files (path, content, language) — large files use file_url' },
  { name: 'ChatMessage', purpose: 'Conversation history (role: user/morpheus, content) — perpetual memory per project' },
  { name: 'FileSnapshot', purpose: 'Point-in-time file snapshots for revert — large snapshots offloaded to file_url' },
  { name: 'UsageRecord', purpose: 'Credit usage log (action_type, credits, metadata with toolchain manifest)' },
  { name: 'Template', purpose: 'Marketplace template (files as JSON, price, stripe_price_id, install_count)' },
  { name: 'Purchase', purpose: 'Template purchase record (buyer, seller, amount, platform_cut, seller_cut, stripe_session_id)' },
  { name: 'UserSettings', purpose: 'Per-user config (AI mode/keys/models, TTS engine, connections JSON)' },
  { name: 'BackendConfig', purpose: 'Per-project backend config (custom_domain, api_keys JSON)' },
  { name: 'RebuildDoc', purpose: 'Rebuild blueprint document (version, content preview, file_url for full doc)' },
  { name: 'User', purpose: 'Built-in user entity (id, email, full_name, role) — read-only via SDK' },
];