// The plugin's own control panel — what makes the standalone app more than a window with nothing in it.
//
// ── WHY A PLUGIN NEEDS A GUI AT ALL, WHICH SOUNDS OBVIOUS AND IS NOT ─────────────────────────────────────
// A DAW draws its own generic panel for any plugin that has none — every parameter as a row of sliders — so
// inside a host, a plugin without a GUI is survivable. A STANDALONE is not a host with a generic panel: it is
// clap-wrapper opening a window and asking the plugin for a `clap_plugin_gui`. Without one there is nothing
// to put in the window, and the user gets sound and no knobs. That is the state this file fixes.
//
// ── NO THIRD-PARTY GUI TOOLKIT, AND THAT IS A DECISION RATHER THAN PURISM ────────────────────────────────
// The obvious choice is an immediate-mode toolkit (Dear ImGui is MIT and would work). It is not taken here
// for three reasons that all point the same way:
//
//   * a toolkit needs a RENDERER — OpenGL, Metal or DirectX — and therefore a GPU context inside a window
//     the HOST owns. That is the single most common source of "the plugin window is black in my DAW", and it
//     is a class of bug that cannot exist if the drawing is the platform's own;
//   * it would add a device-lifetime question to a plugin whose whole build is currently "the CLAP SDK, the
//     wrappers and (maybe) the engine", all pinned and permissive;
//   * the panel is a list of sliders. A platform can draw that in a few hundred lines, and text comes for
//     free from the system font rather than from a baked atlas.
//
// ── IT IS ALSO NOT A SECOND SOURCE OF TRUTH FOR THE PARAMETERS ───────────────────────────────────────────
// The panel asks the plugin's own `clap_plugin_params` extension for the count, the names, the ranges, the
// current values and the display text. It never reads the parameter table directly, which is why it needs no
// header from Plugin.cpp and why a parameter that changes there changes here. That is exactly the interface a
// host uses, so the panel cannot describe a plugin that is not the one running.
//
// ── ⚠️ AND THE ONE PLACE TWO THREADS MEET ────────────────────────────────────────────────────────────────
// A GUI drag runs on the main thread; `process()` runs on the audio thread. Three things happen on a drag, in
// this order, and all three are needed:
//
//   1. the value is handed to Plugin.cpp, which writes it into a slot and raises a flag — the audio thread
//      picks it up at the top of its next block. This is what makes the sound change even in a host that
//      does not echo a plugin-set parameter;
//   2. the same change is pushed to the host as a PARAM_VALUE output event, which is how CLAP says a plugin
//      tells its host that a control moved — without it the host's own automation display and undo would not
//      know;
//   3. the panel redraws from `get_value`, so what you see is what the host actually holds.
//
// See `morpheus_gui_param_set` in Plugin.cpp for why the handover is a flag and a slot rather than a lock:
// the audio thread may not wait for anything, ever.
export const PLUGIN_GUI_APPLE = 'Source/PluginGui.mm';
export const PLUGIN_GUI_STUB = 'Source/PluginGui.cpp';

/** The panel's geometry, in points. One row per parameter, and the view is exactly as tall as they need. */
const ROW = 34;
const PAD = 14;
const WIDTH = 460;
/** Where the slider track starts, and how much room the number on the right gets. */
const TRACK_X = 168;
const VALUE_W = 78;

/**
 * The ObjC++ panel. Compiled only on Apple, where the CLAP window API is Cocoa (`CLAP_WINDOW_API_COCOA`,
 * which is an `NSView *`).
 */
export const pluginGuiApple = `// ${'Source/PluginGui.mm'} — generated by Morpheus. This file is yours: edit it freely, and the build picks
// up your changes. See server/src/lib/pluginGui.js for why it is drawn natively rather than with a toolkit.

#import <Cocoa/Cocoa.h>
#include <clap/clap.h>
#include <string.h>

// The three things this panel needs from the plugin, and nothing else. Declared here rather than in a header
// so that the GUI is one file to add, remove or replace.
extern "C" {
void *morpheus_gui_state(const clap_plugin_t *plugin);
void morpheus_gui_set_state(const clap_plugin_t *plugin, void *state);
void morpheus_gui_param_set(const clap_plugin_t *plugin, clap_id id, double value);
}

#define MORPHEUS_ROW ${ROW}
#define MORPHEUS_PAD ${PAD}
#define MORPHEUS_TRACK_X ${TRACK_X}
#define MORPHEUS_VALUE_W ${VALUE_W}

// The panel's colours. Dark, and the same green the rest of Morpheus uses — a plugin that looks like the
// thing that built it is worth the four lines.
static NSColor *morpheusBg(void) { return [NSColor colorWithCalibratedRed:0.039 green:0.039 blue:0.043 alpha:1.0]; }
static NSColor *morpheusGreen(void) { return [NSColor colorWithCalibratedRed:0.22 green:1.0 blue:0.08 alpha:1.0]; }
static NSColor *morpheusDim(void) { return [NSColor colorWithCalibratedRed:0.10 green:0.24 blue:0.10 alpha:1.0]; }
static NSColor *morpheusText(void) { return [NSColor colorWithCalibratedRed:0.78 green:0.95 blue:0.80 alpha:1.0]; }

@interface MorpheusPanel : NSView {
  const clap_plugin_t *_plugin;
  const clap_plugin_params_t *_params;
  uint32_t _count;
  int _drag;             // the row being dragged, or -1
  NSTimer *_timer;
}
- (instancetype)initWithPlugin:(const clap_plugin_t *)plugin params:(const clap_plugin_params_t *)params;
- (void)stop;
@end

@implementation MorpheusPanel

- (instancetype)initWithPlugin:(const clap_plugin_t *)plugin params:(const clap_plugin_params_t *)params {
  const uint32_t n = params->count(plugin);
  const CGFloat h = MORPHEUS_PAD * 2 + MORPHEUS_ROW * (CGFloat)n;
  if ((self = [super initWithFrame:NSMakeRect(0, 0, ${WIDTH}, h)])) {
    _plugin = plugin;
    _params = params;
    _count = n;
    _drag = -1;
    // ⚠️ COMMON MODES, NOT THE DEFAULT MODE. A scheduled timer fires in NSDefaultRunLoopMode, which STOPS
    // while a window is being dragged or a DAW is in a modal loop — so the knobs would freeze mid-drag, which
    // reads as a broken plugin. This is the one line that makes the panel feel alive.
    _timer = [NSTimer timerWithTimeInterval:1.0 / 30.0 target:self selector:@selector(tick:) userInfo:nil repeats:YES];
    [[NSRunLoop currentRunLoop] addTimer:_timer forMode:NSRunLoopCommonModes];
  }
  return self;
}

- (void)stop {
  [_timer invalidate];
  _timer = nil;
}

- (void)tick:(NSTimer *)t {
  (void)t;
  // Redrawn rather than pushed to: a host may automate a parameter with no mouse involved, and the only
  // source of truth for the current value is the plugin's own params extension.
  [self setNeedsDisplay:YES];
}

// Top-left origin, because it makes the layout arithmetic the same as reading it: row 0 is the top row.
- (BOOL)isFlipped { return YES; }
- (BOOL)acceptsFirstMouse:(NSEvent *)event { (void)event; return YES; }

- (void)drawRect:(NSRect)dirty {
  (void)dirty;
  [morpheusBg() setFill];
  NSRectFill(self.bounds);

  NSDictionary *nameAttrs = @{
    NSFontAttributeName: [NSFont monospacedSystemFontOfSize:10 weight:NSFontWeightRegular],
    NSForegroundColorAttributeName: morpheusText(),
  };
  NSDictionary *valueAttrs = @{
    NSFontAttributeName: [NSFont monospacedSystemFontOfSize:11 weight:NSFontWeightMedium],
    NSForegroundColorAttributeName: morpheusGreen(),
  };
  const CGFloat trackW = self.bounds.size.width - MORPHEUS_TRACK_X - MORPHEUS_VALUE_W - MORPHEUS_PAD;

  for (uint32_t i = 0; i < _count; ++i) {
    clap_param_info_t info;
    memset(&info, 0, sizeof(info));
    if (!_params->get_info(_plugin, i, &info)) continue;
    double value = info.default_value;
    _params->get_value(_plugin, info.id, &value);
    const double span = info.max_value - info.min_value;
    const double t = span > 0.0 ? (value - info.min_value) / span : 0.0;

    const CGFloat y = MORPHEUS_PAD + MORPHEUS_ROW * (CGFloat)i;

    // the name, on the left
    [[NSString stringWithUTF8String:info.name] drawAtPoint:NSMakePoint(12, y + 3) withAttributes:nameAttrs];

    // the track, and the part of it that is filled
    const NSRect track = NSMakeRect(MORPHEUS_TRACK_X, y + 11, trackW, 4);
    [morpheusDim() setFill];
    NSRectFill(track);
    NSRect filled = track;
    filled.size.width = (CGFloat)(trackW * t);
    [morpheusGreen() setFill];
    NSRectFill(filled);

    // the knob. A circle rather than a handle: it reads as a control rather than as a scrollbar.
    const CGFloat knobX = MORPHEUS_TRACK_X + (CGFloat)(trackW * t);
    NSBezierPath *knob = [NSBezierPath bezierPathWithOvalInRect:NSMakeRect(knobX - 6, y + 7, 12, 12)];
    [[NSColor colorWithCalibratedRed:0.02 green:0.06 blue:0.02 alpha:1.0] setFill];
    [knob fill];
    [morpheusGreen() setStroke];
    [knob setLineWidth:2.0];
    [knob stroke];

    // the number, in the parameter's OWN units, from the plugin's own formatter — so the panel cannot show
    // a unit the plugin does not agree with.
    char text[64] = {0};
    if (!_params->value_to_text(_plugin, info.id, value, text, sizeof(text))) {
      snprintf(text, sizeof(text), "%.2f", value);
    }
    NSString *shown = [NSString stringWithUTF8String:text];
    const NSSize size = [shown sizeWithAttributes:valueAttrs];
    [shown drawAtPoint:NSMakePoint(self.bounds.size.width - MORPHEUS_PAD - size.width, y + 2) withAttributes:valueAttrs];
  }
}

// Which row a point is over, or -1. The whole row is the target, not just the track: a control you have to
// aim at is a control that feels broken.
- (int)rowAt:(NSPoint)p {
  if (p.x < MORPHEUS_TRACK_X - 8) return -1;
  const int i = (int)((p.y - MORPHEUS_PAD) / MORPHEUS_ROW);
  return (i >= 0 && (uint32_t)i < _count) ? i : -1;
}

- (void)setRow:(int)row from:(NSPoint)p {
  if (row < 0) return;
  clap_param_info_t info;
  memset(&info, 0, sizeof(info));
  if (!_params->get_info(_plugin, (uint32_t)row, &info)) return;
  const CGFloat trackW = self.bounds.size.width - MORPHEUS_TRACK_X - MORPHEUS_VALUE_W - MORPHEUS_PAD;
  double t = (double)((p.x - MORPHEUS_TRACK_X) / trackW);
  t = t < 0.0 ? 0.0 : (t > 1.0 ? 1.0 : t);
  const double v = info.min_value + t * (info.max_value - info.min_value);
  morpheus_gui_param_set(_plugin, info.id, v);
  [self setNeedsDisplay:YES];
}

- (void)mouseDown:(NSEvent *)event {
  const NSPoint p = [self convertPoint:[event locationInWindow] fromView:nil];
  // A double-click on a row puts it back where it started. Every hardware control has a way back to its
  // default and a slider otherwise has none but the host's undo.
  if ([event clickCount] == 2) {
    const int row = [self rowAt:p];
    if (row >= 0) {
      clap_param_info_t info;
      memset(&info, 0, sizeof(info));
      if (_params->get_info(_plugin, (uint32_t)row, &info)) {
        morpheus_gui_param_set(_plugin, info.id, info.default_value);
        [self setNeedsDisplay:YES];
      }
      return;
    }
  }
  _drag = [self rowAt:p];
  [self setRow:_drag from:p];
}

- (void)mouseDragged:(NSEvent *)event {
  if (_drag < 0) return;
  [self setRow:_drag from:[self convertPoint:[event locationInWindow] fromView:nil]];
}

- (void)mouseUp:(NSEvent *)event {
  (void)event;
  _drag = -1;
}

@end

// ── the CLAP interface ──────────────────────────────────────────────────────────────────────────────────
namespace {
const clap_plugin_t *g_plugin = nullptr;

bool gui_is_api_supported(const clap_plugin_t *plugin, const char *api, bool is_floating) {
  (void)plugin;
  // EMBEDDED WINDOWS ONLY. A floating window is one the plugin owns and positions itself, which a plugin
  // embedded in a host's own window manager has no business doing — and refusing it here is what lets every
  // host fall back to putting our view inside its window instead.
  if (is_floating) return false;
  return api && !strcmp(api, CLAP_WINDOW_API_COCOA);
}

bool gui_get_preferred_api(const clap_plugin_t *plugin, const char **api, bool *is_floating) {
  (void)plugin;
  *api = CLAP_WINDOW_API_COCOA;
  *is_floating = false;
  return true;
}

bool gui_create(const clap_plugin_t *plugin, const char *api, bool is_floating) {
  if (!gui_is_api_supported(plugin, api, is_floating)) return false;
  const clap_plugin_params_t *params = (const clap_plugin_params_t *)plugin->get_extension(plugin, CLAP_EXT_PARAMS);
  if (!params) return false;
  MorpheusPanel *view = [[MorpheusPanel alloc] initWithPlugin:plugin params:params];
  morpheus_gui_set_state(plugin, (void *)CFBridgingRetain(view));
  g_plugin = plugin;
  return true;
}

MorpheusPanel *panel_of(const clap_plugin_t *plugin) {
  void *state = morpheus_gui_state(plugin);
  return state ? (__bridge MorpheusPanel *)state : nil;
}

void gui_destroy(const clap_plugin_t *plugin) {
  MorpheusPanel *view = panel_of(plugin);
  if (!view) return;
  [view stop];
  [view removeFromSuperview];
  CFRelease((__bridge CFTypeRef)view);
  morpheus_gui_set_state(plugin, nullptr);
  if (g_plugin == plugin) g_plugin = nullptr;
}

bool gui_set_scale(const clap_plugin_t *plugin, double scale) {
  (void)plugin;
  (void)scale;
  // Nothing to do: Cocoa draws in points and the backing store is the screen's. A toolkit with a baked font
  // atlas would have to do arithmetic here; the system font does not.
  return true;
}

bool gui_get_size(const clap_plugin_t *plugin, uint32_t *width, uint32_t *height) {
  MorpheusPanel *view = panel_of(plugin);
  if (!view) return false;
  const NSSize size = view.frame.size;
  *width = (uint32_t)size.width;
  *height = (uint32_t)size.height;
  return true;
}

bool gui_can_resize(const clap_plugin_t *plugin) { (void)plugin; return false; }
bool gui_adjust_size(const clap_plugin_t *plugin, uint32_t *w, uint32_t *h) { (void)plugin; (void)w; (void)h; return false; }
bool gui_set_size(const clap_plugin_t *plugin, uint32_t w, uint32_t h) { (void)plugin; (void)w; (void)h; return false; }
bool gui_set_transient(const clap_plugin_t *plugin, const clap_window_t *w) { (void)plugin; (void)w; return false; }
void gui_suggest_title(const clap_plugin_t *plugin, const char *title) { (void)plugin; (void)title; }

bool gui_set_parent(const clap_plugin_t *plugin, const clap_window_t *window) {
  MorpheusPanel *view = panel_of(plugin);
  if (!view || !window) return false;
  if (!window->api || strcmp(window->api, CLAP_WINDOW_API_COCOA)) return false;
  NSView *parent = (__bridge NSView *)window->cocoa;
  if (!parent) return false;
  // The host hands us its own view; the panel becomes a child of it and fills it. The frame is set from our
  // own size because a host is free to give us a container of any size, and a view that draws outside its
  // bounds is a view that shows the wrong number of rows.
  view.frame = NSMakeRect(0, 0, view.frame.size.width, view.frame.size.height);
  [parent addSubview:view];
  return true;
}

bool gui_show(const clap_plugin_t *plugin) {
  MorpheusPanel *view = panel_of(plugin);
  if (!view) return false;
  [view setHidden:NO];
  [view setNeedsDisplay:YES];
  return true;
}

bool gui_hide(const clap_plugin_t *plugin) {
  MorpheusPanel *view = panel_of(plugin);
  if (!view) return false;
  [view setHidden:YES];
  return true;
}

const clap_plugin_gui_t s_gui = {
  .is_api_supported = gui_is_api_supported,
  .get_preferred_api = gui_get_preferred_api,
  .create = gui_create,
  .destroy = gui_destroy,
  .set_scale = gui_set_scale,
  .get_size = gui_get_size,
  .can_resize = gui_can_resize,
  .adjust_size = gui_adjust_size,
  .set_size = gui_set_size,
  .set_parent = gui_set_parent,
  .set_transient = gui_set_transient,
  .suggest_title = gui_suggest_title,
  .show = gui_show,
  .hide = gui_hide,
};
}  // namespace

extern "C" const clap_plugin_gui_t *morpheus_gui_extension(void) { return &s_gui; }
`;

/**
 * ⚠️ THE OTHER TWO PLATFORMS GET A STUB RATHER THAN A WINDOWS OR X11 PANEL, AND IT RETURNS NULL RATHER THAN A
 * STRUCT THAT SAYS NO.
 *
 * Returning NULL from `get_extension` is the CLAP way to say "this plugin has no GUI", and it is what a host
 * already gets today — so nothing regresses on Windows or Linux, and the DAW's own generic parameter panel is
 * exactly what those users keep. A struct whose `is_api_supported` returns false would be a plugin claiming a
 * capability it does not have, which hosts handle in a variety of imaginative ways.
 *
 * This is a stub with a date on it, not a design: the Windows panel is win32 + GDI and the Linux one is X11,
 * both of the same shape as the Cocoa view above, and both belong in their own change with their own build.
 */
export const pluginGuiStub = `// ${'Source/PluginGui.cpp'} — generated by Morpheus. See server/src/lib/pluginGui.js.
//
// No GUI on this platform yet: Windows and Linux return NULL from CLAP_EXT_GUI, which is how a plugin says it
// has no panel. A DAW then draws its own generic parameter list — the behaviour these platforms have today —
// so this file is the honest "not built here" rather than a plugin that claims a window it cannot draw.

#include <clap/clap.h>

extern "C" const clap_plugin_gui_t *morpheus_gui_extension(void) { return nullptr; }
`;
