// Which Command Deck widget owns which backend endpoint under
// server/src/functions/widget[A-Z]*.js — and which of those endpoints nothing
// owns any more.
//
// WHY THIS EXISTS. buildDeckWidget.js's authoring contract lets a widget build
// create ONE new UI file under src/pages/CommandDeck/widgets/ and, if the widget
// needs it, ONE backend endpoint named `widget<PascalCase>.js` — the naming
// convention enginePolicy.js's WIDGET_BUILD allow-list keys on
// (`/^server\/src\/functions\/widget[A-Z]/`). deleteDeckWidget.js removes the
// widget's .jsx and its one DECK_WIDGETS line, and for a long time nothing
// removed the endpoint, so it outlived the widget that was its only reason to
// exist. A file under server/src/functions/ is ROUTED JUST BY EXISTING —
// routes/functions.routes.js loads `functions/<name>.js` on demand and there is
// no registry to remove — so the leftover was live, reachable surface that
// answered 401 rather than 404. That happened for real:
// server/src/functions/widgetEnergySparkline.js outlived the widget deleted in
// PR #439 and had to be removed by hand (`1a1922b`), whose message records the
// gap as still open.
//
// WHY REMOVING ONE IS THE HONEST FIX, AND WHERE IT STOPS. AGENTS.md treats this
// repository as user-owned application code, and generated code here is
// explicitly the user's (`pluginGui.js`: "generated by Morpheus. This file is
// yours: edit it freely"). So this never removes a file merely because its name
// matches a convention. The endpoint was created by the SAME build, for the SAME
// widget, as the .jsx the delete already removes, and the DECK_WIDGETS entry
// carries the `createdBy` that says whose widget it is — a widget's own generated
// files are the widget's, which is what "delete this widget" means. What this
// refuses to do is take an endpoint that is NOT that widget's: `widgetFunctionsToRemove()`
// only ever names an endpoint the deleted widget's own source invokes, and the
// caller passes every OTHER widget's source so an endpoint another widget still
// calls is never removed with it. A hand-written or shared file is therefore
// preserved by construction, not by a guess.
//
// Pure and import-free on purpose: scripts/verify-deck-widget-backend.mjs runs it
// in CI's no-install guards job, and scripts/guard-mutations.mjs proves the guard
// can go red by breaking one of these functions.

// The invoke shape the build contract produces: base44.functions.invoke('widgetX', …).
// Anchored on the CALL, not on the bare word, so a name mentioned in a comment or
// in prose is not read as a reference — the widget's own header comments name
// their backend file, and that must not count.
const INVOKE = /\b(?:invoke|invokeStream)\s*\(\s*['"](widget[A-Z][A-Za-z0-9]*)['"]/g;

// The convention that makes a function a widget's to begin with
// (enginePolicy.js's WIDGET_BUILD allow-list). A widget may call anything at
// runtime; only a `widget[A-Z]*` name is ever a candidate for removal alongside
// it.
const WIDGET_FUNCTION_NAME = /^widget[A-Z][A-Za-z0-9]*$/;

/**
 * Every widget-owned backend endpoint a widget's own source names, sorted and
 * de-duplicated. Names outside the `widget[A-Z]*` convention are deliberately
 * ignored: a widget calling `deleteDeckWidget` is calling shared code, and that
 * is never this widget's to delete.
 */
export function widgetBackendReferences(source) {
  const names = new Set();
  const text = String(source ?? '');
  INVOKE.lastIndex = 0;
  let match;
  while ((match = INVOKE.exec(text)) !== null) {
    if (WIDGET_FUNCTION_NAME.test(match[1])) names.add(match[1]);
  }
  return [...names].sort();
}

/** The set of endpoint names a group of widget sources names between them. */
export function referencedWidgetFunctions(sources) {
  const referenced = new Set();
  for (const source of sources) {
    for (const name of widgetBackendReferences(source)) referenced.add(name);
  }
  return referenced;
}

/**
 * The endpoints in `fileNames` that nothing references — the orphan class this
 * module exists for. `fileNames` are bare names (no directory, no extension);
 * `sources` are the text of every widget UI file.
 */
export function orphanWidgetFunctions(fileNames, sources) {
  const referenced = referencedWidgetFunctions(sources);
  return [...new Set(fileNames)].filter((name) => !referenced.has(name)).sort();
}

/**
 * The endpoints to remove alongside a deleted widget: the ones the deleted
 * widget's OWN source invokes and no other widget invokes.
 * `otherWidgetSources` must be every OTHER widget UI file's text — that is the
 * half that keeps a shared endpoint alive.
 */
export function widgetFunctionsToRemove(deletedWidgetSource, otherWidgetSources) {
  const stillReferenced = referencedWidgetFunctions(otherWidgetSources);
  return widgetBackendReferences(deletedWidgetSource).filter((name) => !stillReferenced.has(name));
}
