import { createClientFromRequest } from 'npm:@base44/sdk@0.8.40';
import { logUsage } from '../../shared/projectUtils.ts';

// Auto-wires the frontend to the live backend after a successful deploy.
// Reads the live API URL from backend/.deploy.json, then:
//   1. Creates/updates src/api/config.js with the live URL
//   2. Replaces localhost URLs in frontend code with the live URL
//   3. Rewrites relative /api/ calls to use the full live URL
//   4. Updates .env files if they contain API URL variables
// Returns a summary of every file changed and how many replacements were made.

export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const body = await req.json();
    const { projectId } = body;
    if (!projectId) return Response.json({ error: 'projectId required' }, { status: 400 });

    const project = await base44.entities.Project.get(projectId);
    const files = await base44.entities.ProjectFile.filter({ project_id: projectId });

    // Get the live API URL from deploy results
    const deployFile = files.find(f => f.path === 'backend/.deploy.json');
    if (!deployFile) {
      return Response.json({ error: 'No deployment found. Deploy the backend first.' }, { status: 400 });
    }

    const deployInfo = JSON.parse(deployFile.content);
    const apiHostResult = (deployInfo.results || []).find((r: any) =>
      r.component === 'api_host' && r.status === 'deployed' && r.url
    );

    if (!apiHostResult?.url) {
      return Response.json({
        error: 'No live API URL found. The API host must be deployed live (Cloudflare Workers) to auto-wire. Other targets return ZIP/manual deploy.',
      }, { status: 400 });
    }

    // Prefer custom domain — check BackendConfig first (may be set after deploy),
    // then fall back to the domain recorded in deploy metadata
    let customDomain = '';
    try {
      const configRows = await base44.entities.BackendConfig.filter({ project_id: projectId });
      if (configRows[0]?.custom_domain) customDomain = configRows[0].custom_domain;
    } catch {}
    if (!customDomain && apiHostResult.customDomain) customDomain = apiHostResult.customDomain;

    let apiUrl = customDomain ? `https://${customDomain}` : apiHostResult.url;

    // Standalone backend project — no frontend to wire
    if (project.project_type === 'backend') {
      return Response.json({
        apiUrl,
        filesChanged: 0,
        totalReplacements: 0,
        changes: [],
        message: 'Standalone backend project — no frontend to wire. Use the API URL directly in your external app.',
      });
    }

    // 1. Create or update src/api/config.js
    const configPath = 'src/api/config.js';
    const configContent = `// Auto-generated by Morpheus — live backend API URL
// Updated: ${new Date().toISOString()}
// Import this in any frontend file: import { API_BASE_URL } from './api/config'
export const API_BASE_URL = '${apiUrl}';
export default API_BASE_URL;
`;

    const existingConfig = files.find(f => f.path === configPath);
    if (existingConfig) {
      await base44.entities.ProjectFile.update(existingConfig.id, { content: configContent, language: 'javascript' });
    } else {
      await base44.entities.ProjectFile.create({
        project_id: projectId, path: configPath, content: configContent, language: 'javascript'
      });
    }

    // 2. Scan and update frontend files
    const frontendFiles = files.filter(f =>
      !f.path.startsWith('backend/') &&
      !f.path.startsWith('external/') &&
      /\.(js|jsx|ts|tsx|env)$/.test(f.path)
    );

    const changes: any[] = [];
    let totalReplacements = 0;

    for (const file of frontendFiles) {
      let content = file.content;
      let replacements = 0;

      // Pattern 1: Replace localhost URLs with the live URL
      const localhostRegex = /http:\/\/localhost:\d+/g;
      const localhostMatches = content.match(localhostRegex);
      if (localhostMatches) {
        content = content.replace(localhostRegex, apiUrl);
        replacements += localhostMatches.length;
      }

      // Pattern 2: Replace relative /api/ calls with the full live URL
      // Matches: fetch('/api/...'), axios.get('/api/...'), etc.
      // Only the URL string is rewritten, not the function call
      const apiCallRegex = /(['"`])\/api\//g;
      const apiCallMatches = content.match(apiCallRegex);
      if (apiCallMatches) {
        content = content.replace(apiCallRegex, `$1${apiUrl}/api/`);
        replacements += apiCallMatches.length;
      }

      // Pattern 3: Update .env files with API URL variables
      if (file.path.endsWith('.env') || file.path.includes('.env.')) {
        const envPatterns = [
          { regex: /(VITE_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
          { regex: /(REACT_APP_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
          { regex: /(NEXT_PUBLIC_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
          { regex: /(EXPO_PUBLIC_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
        ];
        for (const { regex, replacement } of envPatterns) {
          const matches = content.match(regex);
          if (matches) {
            content = content.replace(regex, replacement);
            replacements += matches.length;
          }
        }
      }

      if (replacements > 0) {
        await base44.entities.ProjectFile.update(file.id, { content });
        changes.push({ path: file.path, replacements });
        totalReplacements += replacements;
      }
    }

    await logUsage(base44, 'autonomous_step', projectId, project.name, {
      phase: 'wire_frontend', apiUrl, filesChanged: changes.length, replacements: totalReplacements
    });

    const message = changes.length > 0
      ? `Wired ${changes.length} frontend file(s) to live backend at ${apiUrl}. ${totalReplacements} API call(s) updated.`
      : `Config file created at ${configPath}. No frontend API calls found to update — import API_BASE_URL from '${configPath}' manually.`;

    return Response.json({
      apiUrl,
      configPath,
      filesChanged: changes.length,
      totalReplacements,
      changes,
      message,
    });
  } catch (error) {
    console.error('Wire frontend error:', error?.message || error);
    return Response.json({ error: error?.message || 'Unknown error' }, { status: 500 });
  }
}