-- One-time migration for the already-provisioned morpheus2 Supabase project,
-- adding the `self_dev_manuals` table for the admin-only "SELF-DEV & ADMIN
-- MANUAL" tool (see schema.prisma's SelfDevManual model comment). Unlike
-- rebuild_docs (a static, hand-authored blueprint), this doc is generated by
-- an AI call that reads the current self-dev/admin source files, and is
-- also regenerated automatically by pushSelfDevToGithub.js whenever a push
-- touches one of those files — trigger/source_hash record why/whether the
-- stored copy is current.
-- Safe to run any time.
-- Run once against the morpheus2 Supabase project (SQL Editor, or
-- `psql "$DATABASE_URL" -f server/prisma/add-self-dev-manual-table.sql`).
-- Skip this if you're initializing a brand-new database from scratch —
-- once this ships, add the same table to manual-supabase-init.sql too.

create table if not exists self_dev_manuals (
  id             text primary key default gen_random_uuid()::text,
  created_by_id  text not null references users(id) on delete cascade,
  version        text not null,
  content        text not null,
  content_size   integer not null default 0,
  file_url       text,
  trigger        text,
  source_hash    text,
  created_date   timestamp(3) not null default now(),
  updated_date   timestamp(3) not null default now()
);
