// Ported from base44/functions/wireFrontendToBackend/entry.ts.
//
// Auto-wires the frontend to the live backend after a successful deploy.
// Reads the live API URL from backend/.deploy.json, then:
//   1. Creates/updates src/api/config.js with the live URL
//   2. Replaces localhost URLs in frontend code with the live URL
//   3. Rewrites relative /api/ calls to use the full live URL
//   4. Updates .env files if they contain API URL variables
// Returns a summary of every file changed and how many replacements were made.
import { prisma } from '../db.js';
import { logUsage } from '../lib/projectUtils.js';

export default async function handler({ user, body }) {
  const { projectId } = body || {};
  if (!projectId) throw Object.assign(new Error('projectId required'), { status: 400 });

  const project = await prisma.project.findFirst({ where: { id: projectId, created_by_id: user.id } });
  if (!project) throw Object.assign(new Error('Project not found'), { status: 404 });

  const files = await prisma.projectFile.findMany({ where: { project_id: projectId, created_by_id: user.id } });

  // Get the live API URL from deploy results
  const deployFile = files.find((f) => f.path === 'backend/.deploy.json');
  if (!deployFile) {
    throw Object.assign(new Error('No deployment found. Deploy the backend first.'), { status: 400 });
  }

  const deployInfo = JSON.parse(deployFile.content);
  const apiHostResult = (deployInfo.results || []).find((r) =>
    r.component === 'api_host' && r.status === 'deployed' && r.url
  );

  if (!apiHostResult?.url) {
    throw Object.assign(new Error('No live API URL found. The API host must be deployed live (Cloudflare Workers) to auto-wire. Other targets return ZIP/manual deploy.'), { status: 400 });
  }

  // Prefer custom domain — check BackendConfig first (may be set after deploy),
  // then fall back to the domain recorded in deploy metadata
  let customDomain = '';
  try {
    const config = await prisma.backendConfig.findFirst({ where: { project_id: projectId, created_by_id: user.id } });
    if (config?.custom_domain) customDomain = config.custom_domain;
  } catch {
    // ignore — fall through to deploy metadata domain
  }
  if (!customDomain && apiHostResult.customDomain) customDomain = apiHostResult.customDomain;

  const apiUrl = customDomain ? `https://${customDomain}` : apiHostResult.url;

  // Standalone backend project — no frontend to wire
  if (project.project_type === 'backend') {
    return {
      apiUrl,
      filesChanged: 0,
      totalReplacements: 0,
      changes: [],
      message: 'Standalone backend project — no frontend to wire. Use the API URL directly in your external app.',
    };
  }

  // 1. Create or update src/api/config.js
  const configPath = 'src/api/config.js';
  const configContent = `// Auto-generated by Morpheus — live backend API URL
// Updated: ${new Date().toISOString()}
// Import this in any frontend file: import { API_BASE_URL } from './api/config'
export const API_BASE_URL = '${apiUrl}';
export default API_BASE_URL;
`;

  const existingConfig = files.find((f) => f.path === configPath);
  if (existingConfig) {
    await prisma.projectFile.update({ where: { id: existingConfig.id }, data: { content: configContent, language: 'javascript' } });
  } else {
    await prisma.projectFile.create({
      data: { created_by_id: user.id, project_id: projectId, path: configPath, content: configContent, language: 'javascript' },
    });
  }

  // 2. Scan and update frontend files
  const frontendFiles = files.filter((f) =>
    !f.path.startsWith('backend/') &&
    !f.path.startsWith('external/') &&
    /\.(js|jsx|ts|tsx|env)$/.test(f.path)
  );

  const changes = [];
  let totalReplacements = 0;

  for (const file of frontendFiles) {
    let content = file.content;
    let replacements = 0;

    // Pattern 1: Replace localhost URLs with the live URL
    const localhostRegex = /http:\/\/localhost:\d+/g;
    const localhostMatches = content.match(localhostRegex);
    if (localhostMatches) {
      content = content.replace(localhostRegex, apiUrl);
      replacements += localhostMatches.length;
    }

    // Pattern 2: Replace relative /api/ calls with the full live URL
    // Matches: fetch('/api/...'), axios.get('/api/...'), etc.
    // Only the URL string is rewritten, not the function call
    const apiCallRegex = /(['"`])\/api\//g;
    const apiCallMatches = content.match(apiCallRegex);
    if (apiCallMatches) {
      content = content.replace(apiCallRegex, `$1${apiUrl}/api/`);
      replacements += apiCallMatches.length;
    }

    // Pattern 3: Update .env files with API URL variables
    if (file.path.endsWith('.env') || file.path.includes('.env.')) {
      const envPatterns = [
        { regex: /(VITE_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
        { regex: /(REACT_APP_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
        { regex: /(NEXT_PUBLIC_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
        { regex: /(EXPO_PUBLIC_API_URL\s*=\s*).*/g, replacement: `$1${apiUrl}` },
      ];
      for (const { regex, replacement } of envPatterns) {
        const matches = content.match(regex);
        if (matches) {
          content = content.replace(regex, replacement);
          replacements += matches.length;
        }
      }
    }

    if (replacements > 0) {
      await prisma.projectFile.update({ where: { id: file.id }, data: { content } });
      changes.push({ path: file.path, replacements });
      totalReplacements += replacements;
    }
  }

  await logUsage(user.id, 'autonomous_step', projectId, project.name, {
    phase: 'wire_frontend', apiUrl, filesChanged: changes.length, replacements: totalReplacements,
  });

  const message = changes.length > 0
    ? `Wired ${changes.length} frontend file(s) to live backend at ${apiUrl}. ${totalReplacements} API call(s) updated.`
    : `Config file created at ${configPath}. No frontend API calls found to update — import API_BASE_URL from '${configPath}' manually.`;

  return {
    apiUrl,
    configPath,
    filesChanged: changes.length,
    totalReplacements,
    changes,
    message,
  };
}
