// Runtime verification for the WordPress pairing flow.
//
// Dependency-free (it reads source, and imports only pure modules), so it runs
// in CI's no-install guards job. Run:  node scripts/verify-pairing.mjs
//
// The pairing code is a CREDENTIAL that mints the shared secret, and it is
// exchanged between two codebases that cannot import each other. So this checks
// two different kinds of thing:
//
//   1. the security rules that are easy to lose in a refactor — constant-time
//      comparison, expiry, single use, a failure limit, a rate limit, and an
//      alphabet with no look-alike characters;
//   2. the wire contract between Morpheus (JS) and the plugin (PHP): the same
//      route, the same request field, the same response field. A rename on one
//      side is a silent 403 at runtime, which is exactly the failure an operator
//      would describe as "it just won't connect".
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { isNewer } from '../server/src/lib/version.js';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(REPO, p), 'utf8');

let checks = 0;
let failures = 0;
function check(name, actual, expected) {
  checks++;
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    console.log(`  PASS  ${name}`);
  } else {
    console.log(`  FAIL  ${name}\n          expected ${e}\n          got      ${a}`);
    failures++;
  }
}
const has = (haystack, needle) => String(haystack).includes(needle);

console.log('\nWordPress pairing — runtime verification\n');

const php = read('wp-plugin/morpheus/includes/class-pairing.php');
const seo = read('wp-plugin/morpheus/includes/seo/class-seo.php');
const settings = read('wp-plugin/morpheus/includes/class-settings.php');
const bootstrap = read('wp-plugin/morpheus/morpheus.php');
const js = read('server/src/lib/wpPlugin.js');
const connect = read('server/src/functions/connectWordPress.js');
const probe = read('server/src/functions/probeWordPress.js');

// ── 1. the plugin is actually wired up ──────────────────────────────────────
console.log('1. the pairing endpoint is loaded and registered');
check('the class is required by the plugin', has(bootstrap, "require_once MORPHEUS_DIR . 'includes/class-pairing.php';"), true);
check('its route is registered on rest_api_init', has(bootstrap, "add_action( 'rest_api_init', array( 'Morpheus_Pairing', 'register_routes' ) );"), true);
check('the route path is /pair', has(php, "register_rest_route( MORPHEUS_REST_NS, '/pair'"), true);
check('/status advertises pairing availability (the wizard keys off it)', has(read('wp-plugin/morpheus/includes/class-rest.php'), "'available' => true"), true);

// ── 2. the security rules ───────────────────────────────────────────────────
console.log('\n2. the code is treated like the credential it is');
check('comparison is constant-time (hash_equals)', has(php, 'hash_equals('), true);
check('the code expires', /const TTL\s*=\s*\d+;/.test(php), true);
check('a wrong code is counted', has(php, '$s[\'failures\']++'), true);
check('failures cancel the code', /failures'\]\s*>=\s*self::MAX_FAILURES/.test(php) || /MAX_FAILURES\s*\)/.test(php), true);
check('there is a per-address rate limit', has(php, 'RATE_MAX') && has(php, 'REMOTE_ADDR'), true);
const handleBody = php.slice(php.indexOf('public static function handle'));
check('the handler was located', handleBody.length > 200, true);
check('a rate-limited caller is turned away before the code is compared', handleBody.indexOf('self::rate_limited()') < handleBody.indexOf('hash_equals('), true);
check('...and before a wrong attempt is counted', handleBody.indexOf('self::rate_limited()') < handleBody.indexOf("$s['failures']++"), true);
check('the code is single use', has(php, "'used'      => true") || has(php, "'used' => true"), true);
check('the secret is generated by the plugin, not chosen by a caller', has(php, 'random_bytes( 24 )'), true);
check('a pairing response never echoes the code back', has(php, "'secret' =>"), true);
check('a disconnect clears the secret as well as the code', /function disconnect[\s\S]*?webhook_secret'\] = ''/.test(php), true);

// The alphabet: no I, L, O, 0 or 1 — read off one screen, typed into another.
const alphabet = (php.match(/const ALPHABET = '([^']+)'/) || [, ''])[1];
check('the alphabet avoids look-alike characters', /^[A-HJ-NP-Z2-9]+$/.test(alphabet), true);
check('the alphabet is long enough to matter', alphabet.length >= 30, true);
check('the code is long enough to matter', /for \( \$i = 0; \$i < 8; \$i\+\+ \)/.test(php), true);

// ── 3. only an administrator can see or rotate a code ───────────────────────
console.log('\n3. only an administrator can reach the controls');
check('the admin action checks the capability', has(settings, "current_user_can( 'manage_options' )"), true);
check('the admin action checks a nonce', has(settings, 'check_admin_referer'), true);
check('the admin panel asks for a code through current_code() (which reissues a dead one)', has(settings, 'Morpheus_Pairing::current_code()'), true);
check('...and never prints the stored code directly', has(settings, "get_option( 'morpheus_pairing'"), false);
check('the panel tells the operator how long the code lasts', has(settings, 'Morpheus_Pairing::seconds_left'), true);

// ── 4. the wire contract between the two codebases ──────────────────────────
console.log('\n4. JS and PHP agree on the wire');
check('JS posts to the same route', has(js, '/wp-json/${WP_NS}/pair'), true);
check('JS sends `code` (what PHP reads)', has(js, 'JSON.stringify({ code:'), true);
check('PHP reads `code`', has(php, "$body['code']"), true);
check('JS reads `secret` from the response', has(js, 'pair.data.secret') || has(connect, 'pair.data.secret'), true);
check('PHP returns `secret`', has(php, "'secret' => $secret"), true);
check("JS relays the plugin's refusal instead of inventing its own message", has(connect, 'pair.data?.message'), true);

// The secret must not travel in clear text: pairing is https-only.
check('pairing refuses a non-https site', has(js, "^https:\\/\\/"), true);
check('...with a local-development exception', has(js, 'localhost'), true);

// ── 5. the wizard's version threshold ───────────────────────────────────────
console.log('\n5. the wizard asks for the right thing');
// The version pairing was INTRODUCED. It must not be bumped along with the
// plugin: a site on 0.5.4 can pair, and telling it to update would be wrong.
const threshold = (probe.match(/const PAIRING_VERSION = '([\d.]+)'/) || [, ''])[1];
check('the pairing threshold is the version pairing shipped in', threshold, '0.5.4');
const current = (bootstrap.match(/Version:\s+([\d.]+)/) || [, ''])[1];
check('the plugin is at or beyond that version', isNewer(current, threshold) || current === threshold, true);
check('the probe tells the wizard to install when the plugin is missing', has(probe, "step: 'install'"), true);
check('the probe tells the wizard to update when it is too old', has(probe, "step: 'update'"), true);
check('the probe asks for a code when pairing is available', has(probe, "step: 'pair'"), true);
check('the probe distinguishes unreachable from not-installed', has(probe, "step: 'unreachable'"), true);
// Recognising WordPress itself: the REST discovery header is the signature, not
// a guess from the body — guessing told real WordPress sites they were not
// WordPress (found by probing a plugin-less install).
check('the probe recognises WordPress by its REST discovery header', has(probe, 'api.w.org'), true);
check('...and reports which evidence it used', has(probe, 'wordpress_evidence'), true);
check('the plugin client captures that header', has(js, "res.headers.get('link')"), true);

// The probe's own version comparison — the thing that would send someone on a
// current build round the update loop.
check('version compare: 0.5.4 is newer than 0.5.3', isNewer('0.5.4', '0.5.3'), true);
check('version compare: equal is not newer', isNewer('0.5.4', '0.5.4'), false);
check('version compare: double digits', isNewer('0.5.10', '0.5.9'), true);
check('version compare: missing parts', isNewer('0.6', '0.5.4'), true);
check('version compare: junk is not newer', isNewer('', '0.5.4'), false);

// ── 6. the install step: as close to one step as WordPress allows ───────────
console.log('\n6. the install step offers every route, and claims no more');
const panel = read('src/components/matrix/website/SetupTab.jsx');
const packer = read('scripts/pack-wp-plugin.mjs');
const readme = read('wp-plugin/morpheus/readme.txt');

// The download link and the WP-CLI command must point at the SAME file. They
// are written in two places, so this is exactly the kind of pair that drifts.
const zipConst = (panel.match(/const PLUGIN_ZIP = '([^']+)'/) || [, ''])[1];
const zipUrlConst = (panel.match(/const PLUGIN_ZIP_URL = `([^`]+)`/) || [, ''])[1];
const cliLine = (panel.match(/const WP_CLI_INSTALL = `([^`]+)`/) || [, ''])[1];
check('the panel serves the zip from this build', zipConst, '/morpheus-wordpress-plugin.zip');
// It is written as a template, so assert the STRUCTURE: the production origin
// plus an interpolation of the same-origin path. A hardcoded second path would
// fail here.
check('the absolute URL is the production origin plus that same path', zipUrlConst, 'https://morpheus.nz${PLUGIN_ZIP}');
check('the WP-CLI command names a plugin to install', has(cliLine, 'wp plugin install'), true);
check('...using that one absolute URL (so it can only name the same file)', has(cliLine, '${PLUGIN_ZIP_URL}'), true);
check('...and activates it', has(cliLine, '--activate'), true);

// The hand-off has to be complete enough to send on its own.
const handoff = (panel.match(/function handOffMessage\([\s\S]*?\n\}/) || [''])[0];
check('the hand-off message carries the plugin file', has(handoff, 'WP_CLI_INSTALL') || has(handoff, zipConst), true);
check('...the upload page', has(handoff, 'plugin-install.php?tab=upload'), true);
check('...and where the pairing code comes from', has(handoff, 'options-general.php?page=morpheus'), true);
check('...and says no passwords are needed', has(handoff, 'no passwords'), true);

// The honest limit, stated in the UI rather than left as a mystery.
check('the panel says WordPress requires an administrator', has(panel, 'only installs plugins for an administrator'), true);
check('the panel promises never to ask for a WordPress password', has(panel, 'never asks for your WordPress password'), true);
check('the manual path is ordered and confirms the download', has(panel, '1. Download the plugin') && has(panel, '1. Downloaded'), true);
check('a copy button falls back rather than dying where the clipboard is blocked', has(panel, 'catch { /* the block below stays selectable */ }'), true);

// readme.txt is what WordPress shows on the plugin screen, and a stable tag
// that disagrees with the header is a classic silent drift.
const headerVersion = (bootstrap.match(/Version:\s+([\d.]+)/) || [, ''])[1];
const stableTag = (readme.match(/Stable tag:\s*([\d.]+)/) || [, ''])[1];
check('the plugin has a readme for the WordPress plugin screen', readme.length > 500, true);
check('its stable tag matches the plugin header', stableTag, headerVersion);
// The header and the readme were checked; the runtime CONSTANT was not, and it is
// the one that does damage. MORPHEUS_VERSION is what /status reports to Morpheus
// and what class-updates.php compares an update manifest against, so a constant
// lagging the header makes is_newer( manifest, running ) permanently true: every
// site is offered an update it already has, forever. That happened (0.6.3 against
// a 0.6.4 header) and nothing failed. Three copies of one fact, so check three.
const constantVersion = (bootstrap.match(/MORPHEUS_VERSION',\s*'([\d.]+)'/) || [, ''])[1];
check('it reads a runtime version constant (parser sanity)', /^\d+\.\d+\.\d+$/.test(constantVersion), true);
check('the runtime version constant matches the plugin header', constantVersion, headerVersion);
check('it documents the connection step', has(readme, 'Settings → Morpheus'), true);
check('it documents the deploy deny-list', has(readme, 'wp-config.php'), true);
check('its changelog covers the shipped versions', has(readme, '= 0.5.0 =') && has(readme, `= ${headerVersion} =`), true);
check('the readme travels inside the plugin zip', has(packer, "rmSync(resolve(staging, 'morpheus/tests')"), true);

// ⭐ AND THE THING THAT MADE THE TWO-CANONICAL FIX UNDELIVERABLE: a change with no version bump.
//
// Every version string agreed — header, constant, stable tag, changelog — and the fix still could not reach a
// single site, because the whole update channel is VERSION-COMPARED. Rob's words: *"both the Morpheus site and
// wordpress dont give me update options."* The one place the question can be answered is at pack time, where the
// published manifest is reachable, and this is the predicate it uses.
const { undeliverable } = await import('./lib/wpPluginRelease.mjs');
const published = { version: '0.8.5', sha256: 'f'.repeat(64) };
check('a plugin change with the version bumped is deliverable',
  undeliverable(published, { version: '0.8.6', sha256: 'a'.repeat(64) }), null);
check('…an identical rebuild at the same version is deliverable (nothing changed)',
  undeliverable(published, { version: '0.8.5', sha256: 'f'.repeat(64) }), null);
check('…and a change at the SAME version is refused, because no site would ever be offered it',
  /changed but the version did not/.test(undeliverable(published, { version: '0.8.5', sha256: 'a'.repeat(64) }) || ''), true);
check('…while an unknown published manifest is not a build failure — it says nothing rather than guessing',
  undeliverable(null, { version: '0.8.5', sha256: 'a'.repeat(64) }), null);
// The packer must actually USE it, or the predicate is a unit test with nothing behind it.
// ⭐ AND THE PLUGIN MUST DESCRIBE ARCHIVES, NOT ONLY SINGLE POSTS. This is a STRUCTURAL check and it is worth
// being honest about why: the behaviour it stands for — an archive getting exactly one canonical with the query
// string stripped, a description from a real source, and og tags — is asserted in
// `wp-plugin/morpheus/tests/harness-noyoast.php`, which needs a real WordPress and is HAND-RUN (Playground, WASM
// PHP). CI has no PHP, so what it can hold is that the branch still exists. It did not: `emit_head()` returned
// early on anything that was not a single post, and the live store's `/shop/` shipped with no canonical, no
// description and no social tags for as long as that was true.
check('the plugin describes ARCHIVES as well as single posts',
  has(seo, 'self::is_archive_view()') && has(seo, 'private static function emit_archive_head()'), true);
check('…and an archive canonical ignores the query string, which is what collapses ?orderby= near-duplicates',
  has(seo, 'private static function archive_canonical()') && has(seo, 'user_trailingslashit( \'page/\' . $paged )'), true);
check('…from a real source, in order, and nothing invented when all four are empty',
  has(seo, "term_description( $term->term_id, $term->taxonomy )")
  && has(seo, "wc_get_page_id( 'shop' )")
  && has(seo, "$tagline === '' ? '' : $tagline"), true);
// A description written in the page builder is a SHORTCODE, and the strip-only version served those literal
// characters as the meta description of three live category pages (`[html_block id="2419"]`). Both halves are
// asserted: the registered one is RENDERED, and a leftover shortcode-shaped token is removed — because
// `strip_shortcodes()` only knows the REGISTERED ones and passes the rest straight through, which the Playground
// harness proved on the first run of that assertion.
check('…and a page-builder shortcode is RENDERED into the tag, not printed as the shortcode itself',
  has(seo, 'do_shortcode( $raw )') && has(seo, "preg_replace( '/\\[[a-z0-9_-]+"), true);

check('the packer refuses to publish an undeliverable build',
  has(packer, 'undeliverable(live, next)') && has(packer, 'REFUSING TO PUBLISH'), true);

console.log(`\n${checks - failures}/${checks} checks passed`);
if (failures) {
  console.log('\nThe pairing flow is broken or the two sides disagree. Fix before merging.\n');
  process.exit(1);
}
console.log('pairing holds.\n');
