// Runtime verification for the WordPress pairing flow.
//
// Dependency-free (it reads source, and imports only pure modules), so it runs
// in CI's no-install guards job. Run:  node scripts/verify-pairing.mjs
//
// The pairing code is a CREDENTIAL that mints the shared secret, and it is
// exchanged between two codebases that cannot import each other. So this checks
// two different kinds of thing:
//
//   1. the security rules that are easy to lose in a refactor — constant-time
//      comparison, expiry, single use, a failure limit, a rate limit, and an
//      alphabet with no look-alike characters;
//   2. the wire contract between Morpheus (JS) and the plugin (PHP): the same
//      route, the same request field, the same response field. A rename on one
//      side is a silent 403 at runtime, which is exactly the failure an operator
//      would describe as "it just won't connect".
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { isNewer } from '../server/src/lib/version.js';

const REPO = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => readFileSync(join(REPO, p), 'utf8');

let checks = 0;
let failures = 0;
function check(name, actual, expected) {
  checks++;
  const a = JSON.stringify(actual);
  const e = JSON.stringify(expected);
  if (a === e) {
    console.log(`  PASS  ${name}`);
  } else {
    console.log(`  FAIL  ${name}\n          expected ${e}\n          got      ${a}`);
    failures++;
  }
}
const has = (haystack, needle) => String(haystack).includes(needle);

console.log('\nWordPress pairing — runtime verification\n');

const php = read('wp-plugin/morpheus/includes/class-pairing.php');
const settings = read('wp-plugin/morpheus/includes/class-settings.php');
const bootstrap = read('wp-plugin/morpheus/morpheus.php');
const js = read('server/src/lib/wpPlugin.js');
const connect = read('server/src/functions/connectWordPress.js');
const probe = read('server/src/functions/probeWordPress.js');

// ── 1. the plugin is actually wired up ──────────────────────────────────────
console.log('1. the pairing endpoint is loaded and registered');
check('the class is required by the plugin', has(bootstrap, "require_once MORPHEUS_DIR . 'includes/class-pairing.php';"), true);
check('its route is registered on rest_api_init', has(bootstrap, "add_action( 'rest_api_init', array( 'Morpheus_Pairing', 'register_routes' ) );"), true);
check('the route path is /pair', has(php, "register_rest_route( MORPHEUS_REST_NS, '/pair'"), true);
check('/status advertises pairing availability (the wizard keys off it)', has(read('wp-plugin/morpheus/includes/class-rest.php'), "'available' => true"), true);

// ── 2. the security rules ───────────────────────────────────────────────────
console.log('\n2. the code is treated like the credential it is');
check('comparison is constant-time (hash_equals)', has(php, 'hash_equals('), true);
check('the code expires', /const TTL\s*=\s*\d+;/.test(php), true);
check('a wrong code is counted', has(php, '$s[\'failures\']++'), true);
check('failures cancel the code', /failures'\]\s*>=\s*self::MAX_FAILURES/.test(php) || /MAX_FAILURES\s*\)/.test(php), true);
check('there is a per-address rate limit', has(php, 'RATE_MAX') && has(php, 'REMOTE_ADDR'), true);
const handleBody = php.slice(php.indexOf('public static function handle'));
check('the handler was located', handleBody.length > 200, true);
check('a rate-limited caller is turned away before the code is compared', handleBody.indexOf('self::rate_limited()') < handleBody.indexOf('hash_equals('), true);
check('...and before a wrong attempt is counted', handleBody.indexOf('self::rate_limited()') < handleBody.indexOf("$s['failures']++"), true);
check('the code is single use', has(php, "'used'      => true") || has(php, "'used' => true"), true);
check('the secret is generated by the plugin, not chosen by a caller', has(php, 'random_bytes( 24 )'), true);
check('a pairing response never echoes the code back', has(php, "'secret' =>"), true);
check('a disconnect clears the secret as well as the code', /function disconnect[\s\S]*?webhook_secret'\] = ''/.test(php), true);

// The alphabet: no I, L, O, 0 or 1 — read off one screen, typed into another.
const alphabet = (php.match(/const ALPHABET = '([^']+)'/) || [, ''])[1];
check('the alphabet avoids look-alike characters', /^[A-HJ-NP-Z2-9]+$/.test(alphabet), true);
check('the alphabet is long enough to matter', alphabet.length >= 30, true);
check('the code is long enough to matter', /for \( \$i = 0; \$i < 8; \$i\+\+ \)/.test(php), true);

// ── 3. only an administrator can see or rotate a code ───────────────────────
console.log('\n3. only an administrator can reach the controls');
check('the admin action checks the capability', has(settings, "current_user_can( 'manage_options' )"), true);
check('the admin action checks a nonce', has(settings, 'check_admin_referer'), true);
check('the admin panel asks for a code through current_code() (which reissues a dead one)', has(settings, 'Morpheus_Pairing::current_code()'), true);
check('...and never prints the stored code directly', has(settings, "get_option( 'morpheus_pairing'"), false);
check('the panel tells the operator how long the code lasts', has(settings, 'Morpheus_Pairing::seconds_left'), true);

// ── 4. the wire contract between the two codebases ──────────────────────────
console.log('\n4. JS and PHP agree on the wire');
check('JS posts to the same route', has(js, '/wp-json/${WP_NS}/pair'), true);
check('JS sends `code` (what PHP reads)', has(js, 'JSON.stringify({ code:'), true);
check('PHP reads `code`', has(php, "$body['code']"), true);
check('JS reads `secret` from the response', has(js, 'pair.data.secret') || has(connect, 'pair.data.secret'), true);
check('PHP returns `secret`', has(php, "'secret' => $secret"), true);
check("JS relays the plugin's refusal instead of inventing its own message", has(connect, 'pair.data?.message'), true);

// The secret must not travel in clear text: pairing is https-only.
check('pairing refuses a non-https site', has(js, "^https:\\/\\/"), true);
check('...with a local-development exception', has(js, 'localhost'), true);

// ── 5. the wizard's version threshold ───────────────────────────────────────
console.log('\n5. the wizard asks for the right thing');
// The version pairing was INTRODUCED. It must not be bumped along with the
// plugin: a site on 0.5.4 can pair, and telling it to update would be wrong.
const threshold = (probe.match(/const PAIRING_VERSION = '([\d.]+)'/) || [, ''])[1];
check('the pairing threshold is the version pairing shipped in', threshold, '0.5.4');
const current = (bootstrap.match(/Version:\s+([\d.]+)/) || [, ''])[1];
check('the plugin is at or beyond that version', isNewer(current, threshold) || current === threshold, true);
check('the probe tells the wizard to install when the plugin is missing', has(probe, "step: 'install'"), true);
check('the probe tells the wizard to update when it is too old', has(probe, "step: 'update'"), true);
check('the probe asks for a code when pairing is available', has(probe, "step: 'pair'"), true);
check('the probe distinguishes unreachable from not-installed', has(probe, "step: 'unreachable'"), true);

// The probe's own version comparison — the thing that would send someone on a
// current build round the update loop.
check('version compare: 0.5.4 is newer than 0.5.3', isNewer('0.5.4', '0.5.3'), true);
check('version compare: equal is not newer', isNewer('0.5.4', '0.5.4'), false);
check('version compare: double digits', isNewer('0.5.10', '0.5.9'), true);
check('version compare: missing parts', isNewer('0.6', '0.5.4'), true);
check('version compare: junk is not newer', isNewer('', '0.5.4'), false);

console.log(`\n${checks - failures}/${checks} checks passed`);
if (failures) {
  console.log('\nThe pairing flow is broken or the two sides disagree. Fix before merging.\n');
  process.exit(1);
}
console.log('pairing holds.\n');
